### PR TITLE
perf(core): optimize "response.exit"

### PR DESCRIPTION
**Pull request by xuruidong**
### Description

optimize `core.response.exit`
- remove a string concatenation.
- pass the output table to `ngx.print` directly

Fixes # (issue)

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by xuruidong** [comment]
By the way, is it necessary to implement the `core.response.exit` as a vararg function?
There are some strange usages:
```
core.response.exit(200, { message = "msg1" }, "string-arg")
core.response.exit(200, { message = "msg1" }, { message2 = "msg2" })
```
I think `core.response.exit(status_code, data)` is enough. If the function declaration can be simplified, maybe the `for-loop` and `encode_json`  in `core.response.exit` can be removed.

**Review by monkeyDluffy6017 — APPROVED** [review]

**Comment by monkeyDluffy6017** [comment]
> 

You could have a try

**Comment by monkeyDluffy6017** [comment]
> By the way, is it necessary to implement the `core.response.exit` as a vararg function? There are some strange usages:
> 
> ```
> core.response.exit(200, { message = "msg1" }, "string-arg")
> core.response.exit(200, { message = "msg1" }, { message2 = "msg2" })
> ```
> 
> I think `core.response.exit(status_code, data)` is enough. If the function declaration can be simplified, maybe the `for-loop` and `encode_json` in `core.response.exit` can be removed.

You could have a try

**Comment by xuruidong** [comment]
> By the way, is it necessary to implement the `core.response.exit` as a vararg function? There are some strange usages:
> 
> ```
> core.response.exit(200, { message = "msg1" }, "string-arg")
> core.response.exit(200, { message = "msg1" }, { message2 = "msg2" })
> ```
> 
> I think `core.response.exit(status_code, data)` is enough. If the function declaration can be simplified, maybe the `for-loop` and `encode_json` in `core.response.exit` can be removed.

The purpose of the function should be to reduce the concatenation of strings, such as the usage shown below.
```
core.response.exit(200, "string1", "string2", "string3")
```
So , maintain the present state.

**Review by shreemaan-abhishek — APPROVED** [review]

**Comment by monkeyDluffy6017** [comment]
@xuruidong Could you merge the master branch, the ci failed all the time

**Comment by xuruidong** [comment]
> @xuruidong Could you merge the master branch, the ci failed all the time

done

**Pull request merged**
