### PR TITLE
feature: added to limit req based on the request header and request parameters.

### PR DESCRIPTION
**Pull request by gy09535**
### What this PR does / why we need it:
we can use  request parameters and headers to limit req.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by moonming** [comment]
@gy09535 Apache APISIX already support all nginx variables as limit key: http://nginx.org/en/docs/varindex.html, you just need to add it in the enum list of key: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-req.lua#L29.

**Comment by moonming** [comment]
> @gy09535 Apache APISIX already support all nginx variables as limit key: http://nginx.org/en/docs/varindex.html, you just need to add it in the enum list of key: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-req.lua#L29.

It's a good idea to write in the doc.

**Comment by gy09535** [comment]
Sentinel has  implementation this requirement. according to https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0, I  think it is very useful.

**Comment by gy09535** [comment]
> > @gy09535 Apache APISIX already support all nginx variables as limit key: http://nginx.org/en/docs/varindex.html, you just need to add it in the enum list of key: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-req.lua#L29.
> 
> It's a good idea to write in the doc.

Sentinel has  implementation this requirement. according to https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0, I  think it is very useful.

**Pull request closed without merging**
