### PR TITLE
docs: fix spelling errors

### PR DESCRIPTION
**Pull request by gxlct008**
gPRC  ----> gRPC

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by moonming — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Comment by spacewander** [comment]
Please merge master to make CI pass.

**Comment by membphis** [comment]
ping @gxlct008

**Comment by Yiyiyimu** [comment]
ping @gxlct008

**Comment by juzhiyuan** [comment]
Hi, I see you have deleted the repo 🤔 then this PR cannot get updated IMO. We may close it & resubmit a new one.

**Pull request closed without merging**
