### PR TITLE
docs: fix indent in encrypted-storage-fields

### LINKED ISSUE #8796: docs(plugin-develop): wrong indent in encrypted-storage-fields
### Current State

- https://apisix.apache.org/docs/apisix/plugin-develop/#encrypted-storage-fields

```yaml
apisix:
    data_encryption:
    enable: true
    keyring:
        - edd1c9f0985e76a2
        - qeddd145sfvddff4
```

### Desired State

maybe something like below.

```
apisix:
  data_encryption:
    enable: true
    keyring:
      - edd1c9f0985e76a2
      - qeddd145sfvddff4
```

### PR DESCRIPTION
**Pull request by Amishakumari544**
### Description

Fixes #8796 

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

cc - @moonming @navendu-pottekkat

### CODE REVIEW

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]
Please remove the unrelated changes. Switch to master branch, update it to upstream, create a new branch from the master, make changes, commit and pull request.

**Comment by Amishakumari544** [comment]
> Please remove the unrelated changes. Switch to master branch, update it to upstream, create a new branch from the master, make changes, commit and pull request.

Is it fine now? @navendu-pottekkat

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
@bzp2010 Could you do a quick review and merge?

**Review by tzssangglass — APPROVED** [review]

**Comment by tzssangglass** [comment]
and the format of `data_encryption` in https://github.com/apache/apisix/blob/master/docs/zh/latest/plugin-develop.md also need to be fix

**Comment by Ajay-singh1** [comment]
@bzp2010 Approve this changes and merge.

**Pull request merged**
