### PR TITLE
feat: docker image creation from local codebase

### LINKED ISSUE #9541: Cannot build APISIX image
### Description

When trying to build my custom image from source code, i ran the command `make deps` and encounter this error, can someone help me ? 
```
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/share/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [Makefile:152: deps] Error 1

```

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

Support creation of docker image from local codebase.

Fixes #9541

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
It looks great, Setting up APISIX is a bit complicated, but the all steps are in the https://github.com/apache/apisix/blob/master/ci/linux_openresty_common_runner.sh.
We could follow that step by step.
This file is hard to maintain.

**Comment by An-DJ** [comment]
👍 Nice work !

Is it packaged into both amd64 and arm arch docker image, right?

Then mac user could set up their dev environment easily : )

**Comment by shreemaan-abhishek** [comment]
> So i think we could do this in https://github.com/apache/apisix-docker, create a docker image for development when we release apisix.

The idea is to create docker images of the local codebase. If we shift this PR to the `apisix-docker` repository I don't think the creation of docker images of the local codebase can be done.

**Comment by shreemaan-abhishek** [comment]
> Is it packaged into both amd64 and arm arch docker image, right?

It uses apisix-base:dev as the base docker image, so in theory, the created docker image should be of the same CPU architecture as the host machine.

**Comment by shreemaan-abhishek** [comment]
@monkeyDluffy6017 good idea, thanks for the review 🙏🏼

**Comment by shreemaan-abhishek** [comment]
@monkeyDluffy6017 @An-DJ please review: https://github.com/apache/apisix-docker/pull/476

**Pull request closed without merging**
