### PR TITLE
plugin(consumer-restriction): use draft7 way to rewrite the JSON Schema.

### PR DESCRIPTION
**Pull request by Jaycean**
### What this PR does / why we need it:
- fix: #2402 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by juzhiyuan** [comment]
@Jaycean Please have a look at CI.

**Comment by Jaycean** [comment]
> @Jaycean Please have a look at CI.

OK, I'll take a look at the reason. It passed the local test

**Comment by Jaycean** [comment]
According to the previous JSON schema data format, without changing the logic, the current writing method is not the same as the data obtained by the front end. I need to discuss with @liuxiran  again tomorrow

**Review by membphis — APPROVED** [review]

**Comment by juzhiyuan** [comment]
> > @Jaycean Please have a look at CI.
> 
> OK, I'll take a look at the reason. It passed the local test

Well, I will convert this PR to draft.

**Comment by liuxiran** [comment]
> According to the previous JSON schema data format, without changing the logic, the current writing method is not the same as the data obtained by apisix-dashboard. I need to discuss with @liuxiran again tomorrow

@Jaycean 
with the newest json schema
```json
{
	"oneOf": [{
		"properties": {
			"blacklist": {
				"items": {
					"type": "string"
				},
				"minItems": 1,
				"type": "array"
			},
			"rejected_code": {
				"default": 403,
				"minimum": 200,
				"type": "integer"
			},
			"type": {
				"default": "consumer_name",
				"enum": ["consumer_name", "service_id"],
				"type": "string"
			}
		},
		"required": ["blacklist"],
		"title": "blacklist"
	}, {
		"properties": {
			"rejected_code": {
				"default": 403,
				"minimum": 200,
				"type": "integer"
			},
			"type": {
				"default": "consumer_name",
				"enum": ["consumer_name", "service_id"],
				"type": "string"
			},
			"whitelist": {
				"items": {
					"type": "string"
				},
				"minItems": 1,
				"type": "array"
			}
		},
		"required": ["whitelist"],
		"title": "whitelist"
	}],
	"properties": {
		"disable": {
			"type": "boolean"
		}
	},
	"type": "object"
}
```
dashboard can create a route with `key-auth` plugin and `consumer-restriction` plugin successfully. and the `consumer-restriction` plugin can work correctly with the configuration.

If you can change the keys **order** in properties one from current:
`blacklist, rejected_code, type`  to expected `rejected_code, type, blacklist`, that would be better :)

**Comment by juzhiyuan** [comment]
> > According to the previous JSON schema data format, without changing the logic, the current writing method is not the same as the data obtained by apisix-dashboard. I need to discuss with @liuxiran again tomorrow
> 
> @Jaycean
> with your newest json schema
> 
> ```json
> {
> 	"oneOf": [{
> 		"properties": {
> 			"blacklist": {
> 				"items": {
> 					"type": "string"
> 				},
> 				"minItems": 1,
> 				"type": "array"
> 			},
> 			"rejected_code": {
> 				"default": 403,
> 				"minimum": 200,
> 				"type": "integer"
> 			},
> 			"type": {
> 				"default": "consumer_name",
> 				"enum": ["consumer_name", "service_id"],
> 				"type": "string"
> 			}
> 		},
> 		"required": ["blacklist"],
> 		"title": "blacklist"
> 	}, {
> 		"properties": {
> 			"rejected_code": {
> 				"default": 403,
> 				"minimum": 200,
> 				"type": "integer"
> 			},
> 			"type": {
> 				"default": "consumer_name",
> 				"enum": ["consumer_name", "service_id"],
> 				"type": "string"
> 			},
> 			"whitelist": {
> 				"items": {
> 					"type": "string"
> 				},
> 				"minItems": 1,
> 				"type": "array"
> 			}
> 		},
> 		"required": ["whitelist"],
> 		"title": "whitelist"
> 	}],
> 	"properties": {
> 		"disable": {
> 			"type": "boolean"
> 		}
> 	},
> 	"type": "object"
> }
> ```
> 
> dashboard can create a route with `key-auth` plugin and `consumer-restriction` plugin successfully. and the `consumer-restriction` plugin can work correctly with the configuration.
> 
> And what is the purpose of the disable property below, which is not mentioned both in the [doc](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/consumer-restriction.md) and in [test cases](https://github.com/apache/apisix/blob/master/t/plugin/consumer-restriction.t). it would be better to remove if it is no use:)
> cc @juzhiyuan @membphis
> 
> ```json
> "properties": {
> 		"disable": {
> 			"type": "boolean"
> 		}
> 	}
> ```

hi please see here https://github.com/apache/apisix-dashboard/issues/495

**Comment by liuxiran** [comment]
> hi please see here apache/apisix-dashboard#495

so you means  apisix should  not return disable filed until get request when FE needed? @juzhiyuan 

it seems that when the schema of the plugin does not have a `properties` property in the first level of the json schema, the interface returns the data with `disable` field.
related code: https://github.com/membphis/apisix/blob/133b52ec78665b7292af62bab6af6bf981363a42/apisix/plugin.lua#L81
which doesn't seem reasonable, especially after json schema  changed from draft5 to draft7. 
in json schema draft7, the `oneof` `anyof` and `allof` type of schema e.g the schema in pr https://github.com/apache/apisix/pull/2440,whice does not contain `properties` in first level 
cc @Jaycean 

the https://github.com/apache/apisix/issues/2439  may also have something to do with it.

**Comment by juzhiyuan** [comment]
> > hi please see here [apache/apisix-dashboard#495](https://github.com/apache/apisix-dashboard/issues/495)
> 
> so you means apisix should not return disable filed until get request when FE needed? @juzhiyuan
> 
> it seems that when the schema of the plugin does not have a `properties` property in the first level of the json schema, the interface returns the data with `disable` field.
> related code: https://github.com/membphis/apisix/blob/133b52ec78665b7292af62bab6af6bf981363a42/apisix/plugin.lua#L81
> which doesn't seem reasonable, especially after json schema changed from draft5 to draft7.
> in json schema draft7, the `oneof` `anyof` and `allof` type of schema e.g the schema in pr #2440 does not contain `properties` in first level
> cc @Jaycean
> 
> the #2439 may also have something to do with it.

hi @membphis, What do you think?

**Comment by Jaycean** [comment]
> > > hi please see here [apache/apisix-dashboard#495](https://github.com/apache/apisix-dashboard/issues/495)
> > 
> > 
> > so you means apisix should not return disable filed until get request when FE needed? @juzhiyuan
> > it seems that when the schema of the plugin does not have a `properties` property in the first level of the json schema, the interface returns the data with `disable` field.
> > related code: https://github.com/membphis/apisix/blob/133b52ec78665b7292af62bab6af6bf981363a42/apisix/plugin.lua#L81
> > which doesn't seem reasonable, especially after json schema changed from draft5 to draft7.
> > in json schema draft7, the `oneof` `anyof` and `allof` type of schema e.g the schema in pr #2440 does not contain `properties` in first level
> > cc @Jaycean
> > the #2439 may also have something to do with it.
> 
> hi @membphis, What do you think?

Yes, Lua code is in `apisix/apisix/plugin.lua`
I think it's the code's judgment on the current schema structure that needs to be changed
However, I may not have a deep understanding of the whole project and the role of the disable field, so I have not thought about how to change the code logic
```
local function load_plugin(name, plugins_list, is_stream_plugin)
    # line82-88
    if plugin.schema and plugin.schema.type == "object" then
        if not plugin.schema.properties or
           core.table.nkeys(plugin.schema.properties) == 0
        then
            plugin.schema.properties = core.schema.plugin_disable_schema
        end
    end
```

Because in the JSON schema Draft 7, some structures do not contain `properties` in the first layer, but there are `properties` in the second layer, but the logic fails to judge. As a result, some schemas do not need to add the` disable` field

**Comment by juzhiyuan** [comment]
the `disable` filed is an injection for every plugin's jsonschema, just waiting for @membphis's reply :)

**Comment by membphis** [comment]
> the `disable` filed is an injection for every plugin's jsonschema, just waiting for @membphis's reply :)

we do not need to add this `disable` field in schema.

**Comment by Jaycean** [comment]
> > the `disable` filed is an injection for every plugin's jsonschema, just waiting for @membphis's reply :)
> 
> we do not need to add this `disable` field in schema.

OK, this field has no effect on the current pr. it affects all schemas. Do you mean that the current function can directly remove this field? If it can be removed, I will submit a new PR later.

**Comment by membphis** [comment]
> Do you mean that the current function can directly remove this field? 

You haven't added this field yet? I do not find it in the changed files: https://github.com/apache/apisix/pull/2440/files

**Comment by Jaycean** [comment]
> > Do you mean that the current function can directly remove this field?
> 
> You haven't added this field yet? I do not find it in the changed files: https://github.com/apache/apisix/pull/2440/files

My current PR does not modify the logic of this disable field. I intend to submit a new PR for modification

**Comment by membphis** [comment]
thx for your explain

**Comment by liuxiran** [comment]
> My current PR does not modify the logic of this disable field. I intend to submit a new PR for modification
> 
> After all, the logic related to the disable field has nothing to do with the current PR, which first deals with the schema format of the plugin(consumer-restriction)

Eagerly awaiting for a change in logic of this disable field😍, which will allow the dashboard better to use.

**Review by liuxiran — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]
Looks good to me then

**Pull request merged**
