### PR TITLE
feat(authz-keycloak): support token exchange

### PR DESCRIPTION
**Pull request by ohayak**
### Description

Hello,

I'm working on a project using multiple keycloak instances to manage users in different spaces. One master keycloak which used as an Identity Provider (IDP) for all the others (identity brokers). In this scenario, we used the token exchange feature to limit handled tokens to one.   

The token issued by the Identity Provider can not be used to verify permissions on the brokers. Therefore, this token need to be exchanged to against a second token issued by the broker in order to be used by authz-keycloak plugin to verify permissions.

The most elegant way to achieve our goal is to let the plugin handle the exchange. Unfortunately, the plugin didn't support this kind of requests, so I tweaked the plugin to support this feature. 

More details about token exchange are available [here](https://www.keycloak.org/docs/latest/securing_apps/#_token-exchange)

I appreciate your efforts and the time to review my pull request. 

Regards,

### Checklist

- [X] I have explained the need for this PR and the problem it solves
- [X] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [X] I have updated the documentation to reflect this change
- [X] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by ohayak** [comment]
subject_issuer validation not working as expected

**Comment by ohayak** [comment]
Any chance to get this PR reviewed ?

**Comment by tzssangglass** [comment]
hi @ohayak, thanks for your contribution, pls resolve conflicts files first.

**Review by starsz — COMMENTED** [review]
Hi @ohayak .Could you add some test to cover this ?

**Comment by spacewander** [comment]
Please make the CI pass, thanks!

**Pull request closed without merging**
