### PR TITLE
feat: Add route lables to the full log

### LINKED ISSUE #11071: feat: Add route lables to the full log
### Description

routes labels are missing in the full log. adding routes labels is more important for the full log

### PR DESCRIPTION
**Pull request by madhawa-gunasekara**
### Description

Fixes #11071 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by Revolyssup** [comment]
Will you please add a corresponding test case which confirms that log contains the label?

**Comment by madhawa-gunasekara** [comment]
Hi @Revolyssup, 

I added the test case

**Comment by shreemaan-abhishek** [comment]
@madhawa-gunasekara the test cases are failing.

**Comment by madhawa-gunasekara** [comment]
Hi @shreemaan-abhishek 

I fixed it

**Comment by shreemaan-abhishek** [comment]
@madhawa-gunasekara sorry but, we don't need this PR, ref: https://github.com/apache/apisix/issues/11071#issuecomment-2014287614

**Pull request closed without merging**
