### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by Ajay-singh1**
### Description

Fixes # (issue)
#11217 
### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by Ajay-singh1** [comment]
@kayx23 I think we are good to go now.

**Review by kayx23 — CHANGES_REQUESTED** [review]
I don't understand what is being fixed in this PR:

* these changes do not create any functional differences
* these links are not broken to begin with

Please close the PR if no other items to fix.

**Comment by Ajay-singh1** [comment]
I mean the hyperlink forwards to a 404 error page not found I think this should fix that.

**Comment by Ajay-singh1** [comment]
@pottekkat Can you kindly review this?

**Comment by yzeng25** [comment]
Hi @Ajay-singh1 your modifications in files `add-multiple-api-versions.md` and `manage-api-consumers.md` won't fix https://github.com/apache/apisix/issues/11217.

The current links work as expected, see [Manage API Consumers - More Tutorials](https://apisix.apache.org/docs/apisix/tutorials/manage-api-consumers/#more-tutorials) and [Add multiple API versions - Next steps](https://apisix.apache.org/docs/apisix/tutorials/add-multiple-api-versions/#next-steps).

As stated in #11217 , the page is `https://apisix.apache.org/zh/docs/apisix/tutorials/manage-api-consumers/` with `zh` in there. Since there is no zh-cn version of Manage API Consumers and Add multiple API versions pages, you can modify the links there and redirect to the en-us pages.

**Review by yzeng25 — CHANGES_REQUESTED** [review]
Please change your modifications so that this pull request works as expected.

**Comment by Ajay-singh1** [comment]
> Please change your modifications so that this pull request works as expected.

Yeah!Mistake thanks for the feedback I had mistakenly tried to rectify en docs.

**Comment by Ajay-singh1** [comment]
@yzeng25 More work needs to be done their is no chinese versions of the page so we need to wait till that time.Closing this pull request as I don't know how can I link those pages.

**Pull request closed without merging**
