### PR TITLE
feat :health check for stream proxy

### PR DESCRIPTION
**Pull request by redynasc**
### What this PR does / why we need it:
Health check is the basic function required by stream proxy

fix:#2407

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by membphis** [comment]
that is a big feature, I'll take a look at this PR later. 

many thx for your contribution @redynasc

**Comment by redynasc** [comment]
resolve the conflict

**Comment by membphis** [comment]
where is the doc?

image

**Comment by spacewander** [comment]
@redynasc 
Do you have time to continue?

**Pull request closed without merging**
