### PR TITLE
fix: always inject disable field into plugin schema

### PR DESCRIPTION
**Pull request by spacewander**
Fix https://github.com/apache/apisix-dashboard/issues/1227

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
It seems good to me 🤔

**Review by membphis — APPROVED** [review]

**Review by membphis — CHANGES_REQUESTED** [review]
CI failed

**Comment by spacewander** [comment]
@membphis 
CI pass.

**Review by nic-chen — APPROVED** [review]

**Comment by juzhiyuan** [comment]
ping @membphis

**Review by membphis — APPROVED** [review]

**Pull request merged**
