### PR TITLE
feat: install-dependencies switch apisix-base to apisix-runtime

### PR DESCRIPTION
**Pull request by Sn0rt**
### Description

Fixes https://github.com/apache/apisix/issues/10401

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by monkeyDluffy6017 — APPROVED** [review]

**Comment by AlinsRan** [comment]
Why doesn't Debin/Ubuntu use apisix-runtime?

**Comment by Sn0rt** [comment]
> Why doesn't Debin/Ubuntu use apisix-runtime?

I don't know.
Because Ubuntu did not use apisix-base before, I did not replace it with apisix-runtime.

**Comment by AlinsRan** [comment]
Can you replace it?

**Comment by Sn0rt** [comment]
> Can you replace it?

this PR is for replace the original one. if you want modify the ubuntus' we can discuss under another PR.

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
