### PR TITLE
feat(prometheus): Add metric prefix attr

### PR DESCRIPTION
**Pull request by haoxins**
### What this PR does / why we need it:

Make it configurable for prometheus metric prefix

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by spacewander — COMMENTED** [review]
Could you add a test in https://github.com/apache/apisix/blob/master/t/cli/test_prometheus.sh?

**Comment by haoxins** [comment]
> Could you add a test in https://github.com/apache/apisix/blob/master/t/cli/test_prometheus.sh?

@spacewander I need to trigger the CI for my PR, so that I can debug my unit tests?
is there any action can approve the workflows?

**Comment by spacewander** [comment]
> > Could you add a test in [`master`/t/cli/test_prometheus.sh](https://github.com/apache/apisix/blob/master/t/cli/test_prometheus.sh?rgh-link-date=2021-12-30T05%3A30%3A01Z)?
> 
> @spacewander I need to trigger the CI for my PR, so that I can debug my unit tests? is there any action can approve the workflows?

You can run `./t/cli/test_prometheus.sh` directly.

**Comment by haoxins** [comment]
@spacewander the CI passed :)

**Review by tzssangglass — APPROVED** [review]

**Review by spacewander — APPROVED** [review]

**Pull request merged**
