### PR TITLE
feat: grpc-web plugin supports trailers as part of response body

### PR DESCRIPTION
**Pull request by Affanmir**
### Description

Fixes # (issue)

### Checklist

- [X] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [X] I have added tests corresponding to this change
- [] I have updated the documentation to reflect this change
- [X] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by Affanmir** [comment]
@shreemaan-abhishek  https://github.com/apache/apisix/issues/10573 Linked Issue

**Comment by Affanmir** [comment]
This needs some more work, I want to introduce a few more "Access-Control-Allow-Headers" to support different web apps. I'll also want to fix another small issue related to prefix matching paths for routes.

**Comment by monkeyDluffy6017** [comment]
@Affanmir is this pr ready?

**Comment by Vacant2333** [comment]
@Affanmir hello~ whats the status of the pr now, will it be process~

**Comment by Affanmir** [comment]
> @Affanmir hello~ whats the status of the pr now, will it be process~

ready for review and merge

**Comment by shreemaan-abhishek** [comment]
@Affanmir the CI is failing.

**Comment by Affanmir** [comment]
@shreemaan-abhishek can the workflows be rerun? apologies for the delay on my end

**Comment by sheharyaar** [comment]
@Affanmir , can you please list down the tasks that are complete with this PR ?
We can also proceed like this :
1. If you wish to work on the complete PR that is also great
2. If you feel it would take much time, then you can handover the PR and I can continue on this. For this I will need the list of subtasks (completed and remaining ones). Since this is a high priority bug, we would like to fix this fast.

So what do you say ?

**Comment by Affanmir** [comment]
> So what do you say ?

The PR is complete.

What this PR does 
1. Fix missing trailers issue due to inconsistent grpc implementation 
2. Fix prefix matched by path pattern in the path used for patterns with the format <package>.<service>/

Further bugs/features missing in this plugin that you can work on
1. Cors plugin does not work with this plugin
2. GRPC Response codes conversion need to be added

**Comment by sheharyaar** [comment]
@shreemaan-abhishek , please run the workflow.

**Comment by sheharyaar** [comment]
@Affanmir apart from the test-case you created, there should be a test for the grpc-status trailer, as it was encountered in your issue

**Comment by sheharyaar** [comment]
@Affanmir, please run `make lint` and correct the lint issues.

**Comment by sheharyaar** [comment]
> CORS plugin does not work with this plugin

@Affanmir , are you referring to this :
> If a request is made for a resource on another origin which returns [the CORs headers](https://enable-cors.org/), then the type is cors. cors and basic responses are almost identical except that a cors response restricts the headers you can view to Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, and Pragma.

Ref : https://web.dev/articles/introduction-to-fetch#response_types

**Comment by Affanmir** [comment]
> @Affanmir apart from the test-case you created, there should be a test for the grpc-status trailer, as it was encountered in your issue

> Not possible as that would require using a different testing language go's implementation supports this natively, will have to create a java backend.

 >@Affanmir , are you referring to this :
 > Simply put if I want to send headers i.e let's say "device_location" as part of the headers I will get a CORS Access policy denied. cors plugin has a field "allow_headers" even after putting "*" and combining it with the grpc-web plugin I still get the error. The only way I've found to pass aditional headers is to modify the grpc-web plugin which is not the right solution.

**Comment by sheharyaar** [comment]
@Affanmir , please checkout #10851

**Pull request closed without merging**
