### PR TITLE
fix(tracing): should trace request stopped by extern plugin

### PR DESCRIPTION
**Pull request by spacewander**
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by spacewander** [comment]
I don't change the skywalking/opentracing because increasing the priority will make the body_filter call earlier.

Can we remove the `finish` in the body_filter and only finish the span in the log phase?
@dmsolr @yangxikun
Please guide me the right way.

**Comment by spacewander** [comment]
Or maybe we can switch to an onion model for the filter?

**Comment by dmsolr** [comment]
I think finish() should be after `ext-plugin`, but start() should be before `ext-plugin`.
Moving the finish() to the log phase represents increasing the response time in trace view.

the trace includes 2 spans in APISIX, 
the first span, entry span, is over the whole request. It means from the request accepted to the response returned.
the 2nd span, exit span, is only from the sending request to accepting the response.
（Now, those spans start and stop at the same time.）

**Review by tzssangglass — APPROVED** [review]

**Review by shuaijinchao — APPROVED** [review]

**Comment by spacewander** [comment]
I will open another issue to trace https://github.com/apache/apisix/pull/6500#issuecomment-1058748024

**Pull request merged**
