### PR TITLE
docs: Software architecture diagram added

### LINKED ISSUE #5630: docs: add APISIX software architecture diagram
### Improved or typo fixed.

add new diagram before https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/apisix.md#plugin-loading-process

### Solution

APISIX Software Architecture

### PR DESCRIPTION
**Pull request by soham4abc**
### What this PR does / why we need it:

APISIX software architecture diagram added
Fixes #5630 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by soham4abc** [comment]
PTAL @membphis

**Review by spacewander — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]

**Comment by leslie-tsang** [comment]
Hello there, Would give it a try to update [zh docs](https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/apisix.md) at the same time ?

**Review by moonming — APPROVED** [review]

**Comment by moonming** [comment]
> 

we can add issue for Chinese developers

**Comment by soham4abc** [comment]
> Hello there, Would you give it a try to update [zh docs](https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/apisix.md) at the same time ?

Sorry I only understand English and Bengali to a professional level. I will not be able to update `zh-docs`, Extremely sorry!

**Pull request merged**
