### PR TITLE
fix: unnecessary YAML Config reloads

### PR DESCRIPTION
**Pull request by boekkooi-lengoo**
### Description

In order to avoid unnecessary reloading of the yaml configuration. The time used to detect the last change to the config file is changed from `change` which is the time of the last file status change to the `modification` time wich is the time of the last data modification.

For more information also checkout http://lunarmodules.github.io/luafilesystem/manual.html#reference and https://linux.die.net/man/2/stat

Fixes: https://github.com/apache/apisix/issues/9051

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Test cases is needed, you could follow this: https://github.com/apache/apisix/blob/master/t/config-center-yaml/plugin.t

**Comment by boekkooi-lengoo** [comment]
Hey @monkeyDluffy6017,
What type of test case should I add? 
I'm not sure how to best reproduce the issue in a test using lua.

On a related not after reading https://apenwarr.ca/log/20181113 I'm thinking that we should add `inode` and `size` to the version as well. What do you think?

**Comment by monkeyDluffy6017** [comment]
hi @boekkooi-lengoo, try to follow the following test cases:
https://github.com/apache/apisix/blob/master/t/cli/test_standalone.sh

**Comment by shreemaan-abhishek** [comment]
ping @boekkooi-lengoo

**Comment by boekkooi-lengoo** [comment]
@shreemaan-abhishek :ping_pong:

**Comment by monkeyDluffy6017** [comment]
please merge the master

**Comment by boekkooi-lengoo** [comment]
@monkeyDluffy6017 Created merge commit https://github.com/apache/apisix/pull/9065/commits/684c78d829d9acfa0a3df275e20db9d00d0f25f8 as requested

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
