### PR TITLE
feat: support to use upstream_id in stream_route

### PR DESCRIPTION
**Pull request by tokers**
### What this PR does / why we need it:

Currently, we can only use `upstream` inside `stream_route`, although `upstream_id` is a valid field in it, it's not used totally.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Comment by tokers** [comment]
Ping @membphis Please take a look.

**Comment by membphis** [comment]
@tokers you need to resolve the conflict files

**Review by membphis — APPROVED** [review]
we can merge this PR after resolving the conflict files

**Review by tzssangglass — APPROVED** [review]

**Comment by tokers** [comment]
@membphis Conflicts resolved.

**Pull request merged**
