### PR TITLE
fix(openid-connect): return userinfo when use_jwks is true

### LINKED ISSUE #8133: bug: plugin(openid-connect): when set `use_jwks: true`, userinfo is not set
### Current Behavior

When set `use_jwks: true`, the plugin not set userinfo into headers

https://github.com/apache/apisix/blob/23356d6c4a58379f5cf33be92e0d88cc6399a853/apisix/plugins/openid-connect.lua#L228-L240

maybe line 240 should be `return res, err, token, res` ?

### Expected Behavior

userinfo set into headers as x-userinfo

### Error Logs

_No response_

### Steps to Reproduce

configs:
```yaml
routes:
  - uri: 
    plugins:
      openid-connect:
        # https://github.com/apache/apisix/issues/5425
        client_id: xxx
        client_secret: xxx
        discovery: some_host/oidc/.well-known/openid-configuration
        use_jwks: true
        bearer_only: true
        access_token_in_authorization_header: true
        set_userinfo_header: true
```

### Environment

- APISIX version (docker: 2.15.0-alpine):

### PR DESCRIPTION
**Pull request by lovepocky**
### Description

Fixes #8133

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Test case is needed

**Comment by monkeyDluffy6017** [comment]
@lovepocky use this command to run openidc test env `docker run -p 8090:8080  -p 8443:8443 --restart unless-stopped  -d  --env="KEYCLOAK_USER=admin" --env="KEYCLOAK_PASSWORD=123456"  sshniro/keycloak-apisix:1.0.0`, and add the test case to `openid-connect.t`

**Comment by lovepocky** [comment]
Thank you, i will try that later

**Comment by lovepocky** [comment]
Could you suggest a way to check request header like x-userinfo ?

**Comment by tokers** [comment]
> Could you suggest a way to check request header like x-userinfo ?

There are some upstreams in apisix test cases which echo request headers from apisix.

**Comment by g-javi** [comment]
> Could you suggest a way to check request header like x-userinfo ?

@lovepocky Check this [test case](https://github.com/apache/apisix/blob/3887162bc387b89c121f1ccbd823848a388cd6f5/t/plugin/openid-connect.t#L211) and it's expected response

```
--- response_body_like
uri: /uri
cookie: .*
host: 127.0.0.1:1984
user-agent: .*
x-access-token: ey.*
x-id-token: ey.*
x-real-ip: 127.0.0.1
x-refresh-token: ey.*
x-userinfo: ey.*
```

**Comment by monkeyDluffy6017** [comment]
@lovepocky it looks like that your test cases don't pass

**Comment by monkeyDluffy6017** [comment]
@lovepocky Do you have time to fix the failed ci test before merged ?

**Comment by lovepocky** [comment]
> @lovepocky Do you have time to fix the failed ci test before merged ?

sorry, i am busy with work recently.

**Comment by moonming** [comment]
@monkeyDluffy6017 is https://github.com/apache/apisix/pull/8347 cover this PR? should we close this PR?

**Comment by monkeyDluffy6017** [comment]
@moonming this PR should be closed, i fixed this in #8347

**Pull request closed without merging**
