### PR TITLE
docs: populate default log_format for logging plugins

### LINKED ISSUE #9284: docs: populate default `log_format` for logging plugins
Help Wanted. You should review **all log plugin** docs and update them.

### Current State

No default value:
image

For example: https://apisix.apache.org/docs/apisix/plugins/syslog

### Desired State

Populated the field with
`{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}`

### PR DESCRIPTION
**Pull request by Arghyahub**
### Description

As requested on issue #9284 , I have inserted value to the `Default` field of `log_format`

This PR popluates the field with data `{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}`

Fixes #9284 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by kayx23** [comment]
Thanks for the contribution. 

Please update the PR type from `fix` to `docs`.

Also, the original issue mentions a review and update to **all** plugin docs that include this field. Not just the syslog doc.

**Comment by Arghyahub** [comment]
I have updated all plugin docs that includes the field.

**Comment by monkeyDluffy6017** [comment]
@kayx23 please help to review

**Review by kayx23 — APPROVED** [review]
Looks good, thanks!

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]

**Review by leslie-tsang — APPROVED** [review]

**Pull request merged**
