### PR TITLE
docs: make the components of request URL much simpler

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
### What this PR does / why we need it:
fix: #4526 
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by KishaniKandasamy** [comment]
@juzhiyuan @Yiyiyimu @tzssangglass please  give  some review when you are available..

**Review by tzssangglass — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
Hi @KishaniKandasamy it seems the resolution of the image is not so good, compared to [the one](https://github.com/apache/apisix/issues/4526#issuecomment-875753215) you uploaded in the issue. 

Do you mind uploading the new one~

**Comment by tokers** [comment]
@KishaniKandasamy Please resolve the conflicts.

**Comment by KishaniKandasamy** [comment]
> Hi @KishaniKandasamy it seems the resolution of the image is not so good, compared to [the one](https://github.com/apache/apisix/issues/4526#issuecomment-875753215) you uploaded in the issue.
> 
> Do you mind uploading the new one~

@Yiyiyimu  No I don't mind but the preview with this image is
preview
**You meant to make the resolution larger or smaller than this**🤔??

**Review by Yiyiyimu — APPROVED** [review]

**Review by spacewander — APPROVED** [review]

**Pull request merged**
