### PR TITLE
docs: replace stand-alone with standalone

### LINKED ISSUE #9599: docs: replace `stand-alone` with `standalone`
### Current State

Mixed use of two spellings at the moment.

### Desired State

Should stick to `standalone`. Checked references: Microsoft docs, Google docs.

### PR DESCRIPTION
**Pull request by Shivam182**
### Description

Fixes 
#9599

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Hi @Shivam182, I think there are many places that nned to be changed

**Comment by Shivam182** [comment]
Hey @monkeyDluffy6017 , what is the "wait for update" label that you have added here .

**Comment by monkeyDluffy6017** [comment]
Hi @Shivam182, there are many places that need to be modified, please global search

**Comment by Shivam182** [comment]
I did a global search , but found that problems are only inside "blogs" section, not in "docs" section. 
It would be very kind , if you can help me out further , if i am wrong ?

Screenshot 2023-06-11 155607

**Comment by monkeyDluffy6017** [comment]
Git clone the APISIX repository, i did a global search with vscode and found the results below:
image

**Comment by Shivam182** [comment]
Alright , I got it , thanks for helping me out .

**Comment by Shivam182** [comment]
Hey @monkeyDluffy6017 , i have changed the required typos , now when my pull request will get merged ?

**Comment by monkeyDluffy6017** [comment]
Why do you change so many files?

**Pull request closed without merging**
