### PR TITLE
docs: avoid the misleading comment

### LINKED ISSUE #3962: [discuss]: how to make the annotations in the config-default.yaml file clearer
# Description:

Currently, the annotations style in the config-default.yaml file is very misleading, for example:

```yaml
router:
  http: 'radixtree_uri'         # radixtree_uri: match route by uri(base on radixtree)
                                  # radixtree_host_uri: match route by host + uri(base on radixtree)
                                  # radixtree_uri_with_parameter: like radixtree_uri but match uri with parameters,
                                  #   see https://github.com/api7/lua-resty-radixtree/#parameters-in-path for
                                  #   more details.
  ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
# stream_proxy:                 # TCP/UDP proxy
#   tcp:             
```
This annotations style is easy to understand that `stream_proxy` is at the same level as `ssl`, but `stream_proxy` is at the same level as `router`.
I think we need a better way of annotation to make it easier for users to understand the hierarchical relationship before them.
what do you think?

### PR DESCRIPTION
**Pull request by spacewander**
Also remove helpless yaml lint.

Fix #3962
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
Why are you removing this test ?  
Without the YAML lint test on the CI we will probably go backwards.
You can always just ignore YAML files or folders with yamllint or ignore tests in whole files.

The YAML comment syntax is configurable:

Screen Shot 2021-05-06 at 8 48 46 pm

**Comment by spacewander** [comment]
If we ignore it, there is almost nothing left that can be checked.

I quite regard about accepting yamllint. Several months have been passed, it has been proved that the linter is helpless but causes misleading and inconvenient.

**Comment by spacewander** [comment]
Don't try to sell us linter anymore...
We are not an experimental lab for such "modern" technologies.

**Comment by jbampton** [comment]
You are wrong again since the comments disable rule is only one yamllint rule and there are many to check.

There are about 20 yamllint rules :)

Also most of the worlds top projects use yamllint like Apache Airflow and they know it's not helpless.

https://yamllint.readthedocs.io/en/latest/rules.html

Screen Shot 2021-05-06 at 9 15 08 pm

**Review by juzhiyuan — APPROVED** [review]

**Review by Yiyiyimu — APPROVED** [review]

**Pull request merged**
