### PR TITLE
chore: update skywalking plugin to v0.4.1

### LINKED ISSUE #3717: upgrade SkyWalking plugin
Hi, the SkyWalking has released Lua Nginx 0.4.0, we should upgrade plugin's version.

[1] https://skywalking.apache.org/events/release-apache-skywalking-lua-nginx-0.4.0/

### PR DESCRIPTION
**Pull request by stu01509**
### What this PR does / why we need it:

 Update skywalking plugin to v0.4.0 

resolve #3717

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
image

Hi, you could use `fix #xx` to auto-close that issue once this PR gets merged.

**Comment by stu01509** [comment]
> image
> 
> Hi, you could use `fix #xx` to auto-close that issue once this PR gets merged.

Got it, Thanks!

**Comment by spacewander** [comment]
Look like the library should make a new release:
https://github.com/apache/skywalking-nginx-lua/pull/68

**Comment by juzhiyuan** [comment]
ok, just wait for SkyWalking to make a new release.

**Comment by stu01509** [comment]
Hi @juzhiyuan and @spacewander 

So should I close this PR or wait for SkyWalking to release the new version?

**Comment by juzhiyuan** [comment]
no, once it's released, you just need to update the version no IMO

**Comment by spacewander** [comment]
@stu01509 
Try 0.4-1?

**Comment by stu01509** [comment]
Hi @spacewander 

Updated the commit.

cc @juzhiyuan

**Review by tokers — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
