### PR TITLE
WIP - feat(CI): switch to using the GitHub Super-Linter 

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/marketplace/actions/super-linter

Running checks

```
ERROR_ON_MISSING_EXEC_BIT: true
VALIDATE_BASH: true
VALIDATE_BASH_EXEC: true
VALIDATE_EDITORCONFIG: true
VALIDATE_GO: true
VALIDATE_JAVA: true
VALIDATE_JSON: true
VALIDATE_LUA: true
VALIDATE_MARKDOWN: true
VALIDATE_PERL: true
VALIDATE_PYTHON: false
VALIDATE_PYTHON_BLACK: true
VALIDATE_PYTHON_FLAKE8: true
VALIDATE_PYTHON_ISORT: true
VALIDATE_PYTHON_MYPY: true
VALIDATE_PYTHON_PYLINT: true
VALIDATE_SHELL_SHFMT: true
VALIDATE_XML: true
VALIDATE_YAML: true
```

### What this PR does / why we need it:

Lints and standardizes the codebase.

### Pre-submission checklist:

* [X] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by moonming** [comment]
CI failed. @juzhiyuan is github actions limited？

**Comment by juzhiyuan** [comment]
> CI failed. @juzhiyuan is github actions limited？

image

I don't think so, it's failed due to lint errors 🤔

**Comment by spacewander** [comment]
@jbampton has not finished yet, as the "WIP" indicated. We need to be patient.

**Comment by membphis** [comment]
@jbampton you need to rebase your branch

**Comment by jbampton** [comment]
Pinging @spacewander   

Do we have to set this in the repo settings?

From the site: "NOTE: If you pass the Environment variable GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} in your workflow, then the GitHub Super-Linter will mark the status of each individual linter run in the Checks section of a pull request. Without this you will only see the overall status of the full run. There is no need to set the GitHub Secret as it is automatically set by GitHub, it only needs to be passed to the action."

https://github.com/marketplace/actions/super-linter

**Comment by spacewander** [comment]
If `GITHUB_TOKEN` is optional, it would better to omit it.

**Comment by jbampton** [comment]
It looks like it is using the `token` and we don't have to set it.  It outputs the `token` as empty near the top of the run.

By using the `token` it is meant to report back in the `checks` section for each language/check linted separately otherwise we just get the overall check listed in the PR on the main page.  

We seem to have some errors and maybe this is related seen in the image below:

Screen Shot 2021-01-12 at 6 23 26 pm

Seen in the last run -> https://github.com/apache/apisix/pull/3045/checks?check_run_id=1686557482

**Pull request closed without merging**
