### PR TITLE
feat(doc): fix FAQ page error link

### LINKED ISSUE #6920: docs:  The link in 'how-to-reload-your-own-plugin' section of the FAQ page is invalid
### Current State

the link in https://apisix.apache.org/docs/apisix/FAQ#how-to-reload-your-own-plugin is invalid

click the link show

error link url is https://apisix.apache.org/docs/apisix/plugins.md, already invalid In the language state of Chinese, 

### Desired State

Fix the link to correct address

### PR DESCRIPTION
**Pull request by qlql489**
### Description

fix error link in /docs/en/latest/FAQ.md and /docs/zh/latest/FAQ.md
Fixes #6920

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by hf400159** [comment]
The Chinese version has been corrected. https://github.com/apache/apisix/pull/6736

**Comment by Chever-John** [comment]
@qlql489 
Hi, maybe you should refer to @hf400159 's comment.
Just delete the changes in Chinese version.

**Comment by qlql489** [comment]
chinese version is deleted

**Comment by Chever-John** [comment]
request for approval @spacewander @tzssangglass @shuaijinchao @bzp2010

**Review by spacewander — APPROVED** [review]

**Review by hf400159 — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]

**Pull request merged**
