### PR TITLE
feature: support new field  for Service object

### LINKED ISSUE #1573: feature: support new field `host` for Service object
### Issue description
The service object adds a host field. When the route object does not have a host field, the service object can be inherited. 
When the host needs to be changed, only the service can be changed, and it is not necessary to modify all the route host fields.
Structurally, the service object is more like a server in nginx,  the route object is location.

### PR DESCRIPTION
**Pull request by Donghui0**
### Summary

feature: support new field  for Service object

### Issues resolved

Fix #1573

### CODE REVIEW

**Comment by membphis** [comment]
@Donghui0 pls add more test cases about this feature

**Comment by membphis** [comment]
We need to update the router `http/router/radixtree_uri.lua` too.

**Comment by moonming** [comment]
@Donghui0 @membphis please take a look

**Comment by membphis** [comment]
@Donghui0 please add test case, and please take a look at this output of CI.

**Pull request closed without merging**
