### PR TITLE
feat: remove rust dependency by rollback lua-resty-ldap on master

### LINKED ISSUE #9891: feat: As a user, I want to remove rust dependencies, so that reconsider how to install ldap dependencies
### Description

In order to simplify the installation process and improve the efficiency of development and installation.

I want to remove the rust dependency.

curreclty. only LDAP need rust . so we want rollback the package to pure lua version. (need not rust anymore.

### PR DESCRIPTION
**Pull request by Revolyssup**
### Description

Fixes #9891 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by shreemaan-abhishek** [comment]
@Revolyssup, eventually in the future we might have to upgrade `lua-resty-ldap` version again. This doesn't make sense to me as a good solution in the long run.

**Comment by monkeyDluffy6017** [comment]
@shreemaan-abhishek What's your opinion?

**Comment by monkeyDluffy6017** [comment]
@Revolyssup please fix the ci

**Comment by shreemaan-abhishek** [comment]
@monkeyDluffy6017, right now everything is fine CI works well why do we need to remove rust dependency at the first place?

cc: @Sn0rt

**Comment by Revolyssup** [comment]
ldap
@Sn0rt @monkeyDluffy6017 As you can see, a lot of features/fixes have been added after 0.1.0. And most importantly the client module was abstracted so the API changed a little, which means the code would need to be refactored as per the older version. The older version didn't have client.lua. 
What should I do here?

**Comment by Revolyssup** [comment]
To be moved forward after this comment is addressed. https://github.com/apache/apisix/issues/9891#issuecomment-1667209358

**Comment by Revolyssup** [comment]
Current approach: lua-resty-ldap is moved back to v0.1.0 and apisix has been refactored accordingly.

**Review by moonming — APPROVED** [review]

**Review by Sn0rt — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
