### PR TITLE
feat: openid-connect as auth plugin

### PR DESCRIPTION
**Pull request by coiouhkc**
### Description

This PR adds `auth plugin` functionality to openid-connect using `preferred_username` token claim and respective field in consumers to identify and attach the consumer for further needs, e.g. consumer-restriction.

Fixes # (issue)
* #11015 
* #9093 ?

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by coiouhkc** [comment]
Dear maintainers (@kayx23 ?), please advise if the suggested feature is acceptable so that I could continue working on the PR (fix the code, write tests, update docu, etc.)

**Comment by kayx23** [comment]
cc: @shreemaan-abhishek @bzp2010 @moonming

**Comment by coiouhkc** [comment]
@shreemaan-abhishek @bzp2010 @moonming - friendly reminder, please check the suggestion so that I know whether the general direction is OK.

**Comment by rodtelford** [comment]
> riendly reminder, please check the suggestion so that I know whether the general direction is OK.

Hi There. I think this is a great feature. In fact I had modified the authz-keycloak in the same way as I need authorization as well. I would like to be able to do authorization by group memberships reference a claim in the token that list groups.

**Comment by juzhiyuan** [comment]
> repost at https://the-asf.slack.com/archives/CUC5MN17A/p1749188930707309?thread_ts=1749097824.332019&cid=CUC5MN17A

Hi @rodtelford @coiouhkc, several reasons can cause PRs to be processed slowly. Regarding #11490, I believe the maintainers lacked the time to work on it over last year.

If you would like to finish this PR, please submit a new one and let me know here. I will coordinate with some reviewers to take a look at it.

**Comment by rodtelford** [comment]
@coiouhkc - Im keen to pick this up.  I'm also keen in adding authorization based on a configurable field in the token. For example could check for a matching group in groups. Or a matching scope in the scp.

**Comment by coiouhkc** [comment]
@rodtelford - be my guest ;) 
In the project i decided to use another api gateway (KrakenD CE), so i don't have much incentive anymore in following up on this PR.

**Pull request closed without merging**
