### PR TITLE
docs: move "Plugin Config" to "Terminology" sec

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

### Description

Moves the "Plugin Config" page to the "Terminology" section and fixes small issues in the page and the "Plugin" page.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
// @hf400159 @kwanhur @avinal @yzeng25 @juzhiyuan Please review when you are available.

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Comment by kwanhur** [comment]
LGTM

**Review by yzeng25 — APPROVED** [review]
LGTM

**Pull request merged**
