### PR TITLE
feat: avoid overriding customized X-Forwarded-For header

### LINKED ISSUE #8195: bug: proxy-rewrite X-Forwarded-For doesn't work.
### Current Behavior

I have set proxy-rewrite X-Forwarded-For header, but It's still invaild.

### Expected Behavior

_No response_

### Error Logs

_No response_

### Steps to Reproduce

1. Create a route with the X-Forwarded-For of headers rewrited.
2. Send a request through this route, and watch the back-end.

### Environment

- APISIX version (run `apisix version`): 2.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by wangfeng22**
### Description

Fixes #8195

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by tokers — COMMENTED** [review]
Need test cases to cover the changes.

**Comment by wangfeng22** [comment]
> Need test cases to cover the changes.

@tokers  It's similar to #4260, and I don't know how to write test cases.

**Comment by wangfeng22** [comment]
> > @tokers It's similar to #4260, and I don't know how to write test cases.
> 
> read more: https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md#write-test-case

@tzssangglass The test tool does not meet the testing needs, because the `realip_remote_addr` in the returned header is dynamic.

**Comment by tzssangglass** [comment]
> @tzssangglass The test tool does not meet the testing needs, because the `realip_remote_addr` in the returned header is dynamic.

we can change: https://github.com/apache/apisix/blob/024e0ef70b5e403e11eb7a2f4abb59675a657081/apisix/cli/ngx_tpl.lua#L677-L679 and https://github.com/apache/apisix/blob/024e0ef70b5e403e11eb7a2f4abb59675a657081/t/APISIX.pm#L771-L773

**Comment by tzssangglass** [comment]
you can learn from: https://github.com/apache/apisix/pull/8200/files

**Comment by wangfeng22** [comment]
> you can learn from: https://github.com/apache/apisix/pull/8200/files

@tzssangglass Thank you very much. I have added some test cases.

**Pull request closed without merging**
