### PR TITLE
feat: add labels to plugin_config

### PR DESCRIPTION
**Pull request by spacewander**
Also fix the schema validation.

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by nic-chen** [comment]
It seems that this pr supports the definition of labels for `plugin_config`. 

Will it support to match `route` and `plugin_config` through labels in the future?

**Comment by spacewander** [comment]
> Will it support to match route and plugin_config through labels in the future?

No. It is hard to implement and slow to run, and it is not obvious for the users.

**Comment by nic-chen** [comment]
> > Will it support to match route and plugin_config through labels in the future?
> 
> No. It is hard to implement and slow to run, and it is not obvious for the users.

OK

**Review by nic-chen — APPROVED** [review]

**Comment by gxthrj** [comment]
I created a [discuss](https://github.com/apache/apisix/issues/3704) about  using label instead of ID, and I think we can support label match between objects in future :)

**Review by gxthrj — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Pull request merged**
