### PR TITLE
upgrade lua-resty-etcd version

### PR DESCRIPTION
**Pull request by zuiyangqingzhou**
### Description

Fixes https://github.com/apache/apisix/issues/6887

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by tzssangglass** [comment]
From the CI failure message, it seems that it is not possible to upgrade directly on 2.10, APISIX master brance has made more adaptations for the new version of ETCD.

**Comment by zuiyangqingzhou** [comment]
> From the CI failure message, it seems that it is not possible to upgrade directly on 2.10, APISIX master brance has made more adaptations for the new version of ETCD.

But 2.10 is an LTS maintenance release. If you can't update it directly, then how to fix it

**Comment by tzssangglass** [comment]
> > From the CI failure message, it seems that it is not possible to upgrade directly on 2.10, APISIX master brance has made more adaptations for the new version of ETCD.
> 
> But 2.10 is an LTS maintenance release. If you can't update it directly, then how to fix it

backport the changes associated with APISIX, I think this approach is reasonable.

**Comment by zuiyangqingzhou** [comment]
> 



> > > From the CI failure message, it seems that it is not possible to upgrade directly on 2.10, APISIX master brance has made more adaptations for the new version of ETCD.
> > 
> > 
> > But 2.10 is an LTS maintenance release. If you can't update it directly, then how to fix it
> 
> backport the changes associated with APISIX, I think this approach is reasonable.

for version 2.10, does the community have a fix plan?

**Comment by tzssangglass** [comment]
> for version 2.10, does the community have a fix plan?

for version 2.10, the LTS maintenance cycle has come and gone.

If you want to fix this version, at least make APISIX 2.10  works well with this ETCD version.

**Pull request closed without merging**
