### PR TITLE
docs: correct behaviour of body_base64 field in docs

### PR DESCRIPTION
**Pull request by Revolyssup**
### Description
The issue raised here https://github.com/apache/apisix/issues/9561 is due to the confusion around using the `body_base64` field in response-rewrite plugin. The docs currently describe the behaviour falsely as decoding request body instead of body passed in plugin configuration. This PR fixes that.

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by shreemaan-abhishek** [comment]
The correct type would be `docs:` not `fix:`

**Comment by Revolyssup** [comment]
> The correct type would be `docs:` not `fix:`

Thanks

**Review by monkeyDluffy6017 — APPROVED** [review]

**Comment by shreemaan-abhishek** [comment]
@Revolyssup please add the Chinese docs as well.

**Comment by monkeyDluffy6017** [comment]
hi @shreemaan-abhishek It's okay if it's not your native language

**Comment by Revolyssup** [comment]
> hi @shreemaan-abhishek It's okay if it's not your native language

hey @monkeyDluffy6017 , I have added chinese doc as well using google translate. Please confirm if its correct.

**Comment by monkeyDluffy6017** [comment]
deepl is better

**Comment by Revolyssup** [comment]
> deepl is better

Updated it using translation from deepl

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by SylviaBABY — APPROVED** [review]

**Pull request merged**
