### PR TITLE
docs: close example config block

### PR DESCRIPTION
**Pull request by jagedn**
add missing closing quotes in example block

### Description

Improve readability of documentation

There is a code block not ended and documentation doesn't render fine. 

### Checklist

- [X] I have explained the need for this PR and the problem it solves
- [X] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [X] I have updated the documentation to reflect this change
- [X] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by Neilblaze — APPROVED** [review]
LGTM! Thanks 😃

**Review by SylviaBABY — APPROVED** [review]

**Comment by jagedn** [comment]
Not sure if I need to do something now

**Review by Gallardot — APPROVED** [review]
LGTM! Thank you for your contribution.

**Comment by Gallardot** [comment]
@spacewander  
Sorry, I didn't notice that this PR specified to be merged into the release/3.2 branch, which is probably not @jagedn 's intention.
Could this be a wrong operation? Does this situation require a rollback of the PR? I need some guidance. Thanks.

**Comment by jagedn** [comment]
uppss,  

sorry I didn't pay attention to the destination branch. I just followed the "edit this page" button of the page I was reading. 

Let me know if I need to do something

**Comment by kayx23** [comment]
@jagedn yes please have this change merged into the master branch. Might need to reopen a PR. For future refs, theres a button for selecting which branch you want to merge into before opening the PR. 

@Gallardot i made the same mistake just recently merging the change into release 3.2 because I clicked through "edit this page"

**Pull request merged**
