### PR TITLE
fix(elasticsearch-logger): add compatibility headers

### LINKED ISSUE #8647: bug: ElasticSearch logger not working with error Action/metadata line [1] contains an unknown parameter [_type]
### Current Behavior

The plugin eleasticsearch-logger is not working with **elasticseachr-8.x** and **apisix - 3.0.0**
and in apisix it has below error log:
```
2023/01/10 07:51:51 [error] 48#48: *231989 [lua] batch-processor.lua:95: Batch Processor[elasticsearch-logger] failed to process entries: elasticsearch server returned status: 400,
 body: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception",
"reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}, context: ngx.timer, client: , server: 0.0.0.0:9080

```
the plugin conf is referenced to the doc url:
https://apisix.apache.org/docs/apisix/plugins/elasticsearch-logger/
and my conf is:
```
{
  "auth": {
    "password": "changeme",
    "username": "elastic"
  },
  "batch_max_size": 1,
  "buffer_duration": 60,
  "disable": false,
  "endpoint_addr": "http://xxxx:9200",
  "field": {
    "index": "services",
    "type": "collector"
  },
  "inactive_timeout": 5,
  "max_retry_count": 10,
  "name": "elasticsearch-logger",
  "retry_delay": 1,
  "ssl_verify": false,
  "timeout": 60
}
```

I also tried with es 6.0 and same conf as above.
it shows error:
```
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"},"status":400}, context: ngx.timer
```
**Updates:**

It seems the _type is deprecated in es: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-type-field.html#mapping-type-field
After removed the **type** in the conf. It worked.
```
{
  "auth": {
    "password": "changeme",
    "username": "elastic"
  },
  "batch_max_size": 1,
  "buffer_duration": 60,
  "disable": false,
  "endpoint_addr": "http://xxxx:9200",
  "field": {
    "index": "services"
  },
  "inactive_timeout": 5,
  "max_retry_count": 10,
  "name": "elasticsearch-logger",
  "retry_delay": 1,
  "ssl_verify": false,
  "timeout": 60
}
```

### Expected Behavior

The elasticsearch logger plugin should work with es 8.x version.

### Error Logs

See above.

### Steps to Reproduce

1. create a elk cluster using https://github.com/deviantony/docker-elk#bringing-up-the-stack
2. add the elasticsearch logger plugin 
3. check the apisix logs.

### Environment

- APISIX version 3.0.0
- Operating system: centos7

### PR DESCRIPTION
**Pull request by lakshya8066**
### Description

1. Add compatibility headers to ensure smooth transition from version `7.x` to `8.x` 
2. update the elasticsearch in test env

Fixes #8647

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
> This PR changes the version of the elastic search used for testing the elasticsearch-logger plugin to version 8.11.3

I didn't see this?

**Comment by lakshya8066** [comment]
oh my bad, initially this PR was supposed to change the version as well but I am getting errors on upgrading the version. I don't know how to solve the errors.
So for now, I am just adding the headers. I will change the version as soon as I detect the bug

**Comment by monkeyDluffy6017** [comment]
The pr seems not ready if you don't upgrade the elasticsearch

**Comment by shreemaan-abhishek** [comment]
@gaoxingliang please review if you can.

**Review by Revolyssup — APPROVED** [review]
LGTM

**Pull request merged**
