### PR TITLE
feat: upgrade luarocks to 3.8.0 which converts git:// to https://

### PR DESCRIPTION
**Pull request by spacewander**
The Luarocks 2.x is already broken.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by tao12345666333** [comment]
I am not familiar with the operating mechanism of luarocks. :face_exhaling: Is there any explanation or release note for this change?

**Comment by spacewander** [comment]
Luarocks automatically handles the URL conversion in this commit: https://github.com/luarocks/luarocks/commit/9ff512e35455939f02eaec2318e3acc77782fdeb, which is included in v3.8.0. So there is no need to handle this by ourselves.

**Comment by tokers** [comment]
Not sure whether this is good for the user experience as it adds more constraints for the version of luarocks.

**Comment by spacewander** [comment]
No, as I mentioned in the commit message. The luarocks 2.x is actually broken. We just make sure people won't be trapped in it.

**Comment by spacewander** [comment]
The luarocks 2.x doesn't be broken because of the git URL. In fact, it doesn't handle the new rockspec format and the dependency management which have been reported by the user. It has been broken for a time. This PR just admitted it.

**Comment by tokers** [comment]
> No, as I mentioned in the commit message. The luarocks 2.x is actually broken. We just make sure people won't be trapped in it.

Sorry, I misunderstood the meaning of this PR, I thought we add some constraints for the LuaRocks 3.x.

**Review by tokers — APPROVED** [review]

**Review by leslie-tsang — APPROVED** [review]

**Review by membphis — APPROVED** [review]

**Pull request merged**
