### PR TITLE
fix: Update error message when Route doesn't exist

### LINKED ISSUE #2302: request help: failed to match any routes
### Issue description
i create a route like this:

`
{
"uri": "/test",

"methods": ["GET", "POST"],

"plugins": {},

"desc":"hello world",

"remote_addr": "127.0.0.1",

"upstream_id": "13"

}
`

when i curl it, response is:
`
{
"error_msg": "failed to match any routes"
}
`

What does that "error_msg" mean？

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: Linux test 5.4.0-1026-azure #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by liuhengloveyou**
### What this PR does / why we need it:

Fixes #2302 

It used to be "failed to match any routes", now it's "404 Route Not Found"。

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by membphis** [comment]
bad title and commit log style

image

**Comment by liuhengloveyou** [comment]
PS: 
whether the error message needs to be prefixed or not, to distinguish between an apisix error and a business error.

**Comment by moonming** [comment]
@liuhengloveyou please check the commit mesg again, contains Chinese chars.

**Comment by liuhengloveyou** [comment]
> @liuhengloveyou please check the commit mesg again, contains Chinese chars.

updated

**Comment by moonming** [comment]
> > @liuhengloveyou please check the commit mesg again, contains Chinese chars.
> 
> updated

No, the title of PR still has Chinese char.

**Comment by liuhengloveyou** [comment]
> > > @liuhengloveyou please check the commit mesg again, contains Chinese chars.
> > 
> > 
> > updated
> 
> No, the title of PR still has Chinese char.

updated

**Review by moonming — APPROVED** [review]

**Comment by membphis** [comment]
@liuhengloveyou please update the status

image

**Comment by moonming** [comment]
@liuhengloveyou why close this PR?

**Comment by membphis** [comment]
> @liuhengloveyou please update the status

ping @liuhengloveyou

**Comment by liuhengloveyou** [comment]
> > @liuhengloveyou please update the status
> 
> ping @liuhengloveyou

OK

**Comment by membphis** [comment]
@liuhengloveyou pls update your branch.

image

**Review by membphis — APPROVED** [review]
LGTM, after fix the conflicting files, we can merge this PR.

**Pull request merged**
