### PR TITLE
docs: fix admonition in Terminology, Secret

### PR DESCRIPTION
**Pull request by kayx23**
## Before
image
https://apisix.apache.org/docs/apisix/terminology/secret/

## After
See changed file.

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by kayx23** [comment]
Thanks. Merge?
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by kayx23** [comment]
Anybody know why the change is not reflected on the website? I'm still seeing the OG version which is not properly formatted: 
image

https://apisix.apache.org/docs/apisix/terminology/secret/

Confused. Does this mean if I spot a problem on version 3.2, I should commit my change to BOTH version 3.2 and master branch?

**Comment by Neilblaze** [comment]
@kayx23 I hope so, since the preview is being generated from v3.2 & not from master branch.

**Comment by kayx23** [comment]
That's actually quite annoying innit?! Have to open two PRs for the same change? I wonder how many people have committed doc improvements but to the wrong branch....

I was told I shouldn't commit to a specific version, say 3.2, because the change won't be carried over unless I commit to master......

**Comment by Neilblaze** [comment]
I think it's better to push the content to v3.2 & run a cron to migrate files (docs) to the master asynchronously, but yeah I also feel the same.

**Comment by kayx23** [comment]
Maybe we should open a discussion

**Pull request merged**
