### PR TITLE
etcd v3 api support

### PR DESCRIPTION
**Pull request by ChelinTsien**
etcd v3 api support

### CODE REVIEW

**Comment by membphis** [comment]
@ChelinTsien good PR

**Comment by ChelinTsien** [comment]
Because the v3 version of the larger changes, so the v3 interface data format are converted to v2. The test is just through the dashboard to go through the operation of the process once again

**Comment by ChelinTsien** [comment]
in  config.yaml file add :
```
etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://127.0.0.1:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 3 seconds
  protocol : "v3"
  api_prefix : "/v3alpha"   # v3, v3beta,v3alpha etc

```

**Comment by ChelinTsien** [comment]
Added before #1943,  why not review my pr?

**Comment by membphis** [comment]
`add aws sign` why we need this commit?

**Pull request closed without merging**
