### PR TITLE
docs: Fixed doc wording

### PR DESCRIPTION
**Pull request by abs007**
### Description

Corrected doc grammar by changing: "With the Route has created" to "With the Route being created"

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by SylviaBABY — APPROVED** [review]

**Review by navendu-pottekkat — APPROVED** [review]
Thank you for finding and fixing this. LGTM.

**Comment by leslie-tsang** [comment]
Could you help to check if there are similar syntax problems in other files?
Would be too appreciated to do it in one PR with same problems. :)

**Comment by abs007** [comment]
Sure @leslie-tsang, I can take a look at the docs.

**Comment by abs007** [comment]
@leslie-tsang  The link for semantic.yml is broken here: https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#how-to-add-a-new-feature-or-change-an-existing-one

You could provide me the correct link and I can include the fix in this pr

**Comment by leslie-tsang** [comment]
> @leslie-tsang The link for semantic.yml is broken here: https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#how-to-add-a-new-feature-or-change-an-existing-one
> 
> You could provide me the correct link and I can include the fix in this pr

Sorry for the late reply, it looks like it might be better to do this in another PR, after all, it belongs to the link is not working, the new link is [semantic.yml](https://github.com/apache/apisix/blob/master/.github/workflows/semantic.yml)

**Comment by abs007** [comment]
@leslie-tsang No worries. I'll create a new draft pr with this fix and other errors that I may find. 

> the new link is [semantic.yml](https://github.com/apache/apisix/blob/master/.github/workflows/semantic.yml)

Should the fix for this be pushed against the master/next branch?

**Pull request merged**
