### PR TITLE
docs: correct rate in `limit-req` plugin example

### PR DESCRIPTION
**Pull request by MrLinMH**
### Description

Modify the limit-req plugin example

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by kayx23 — COMMENTED** [review]
Thanks. Could you update the English doc for the same too?

**Review by moonming — APPROVED** [review]

**Comment by MrLinMH** [comment]
> Thanks. Could you update the English doc for the same too?

Okay, I'll submit a new PR later.

**Comment by kayx23** [comment]
Please use the same PR.

**Comment by MrLinMH** [comment]
> Please use the same PR.

@kayx23 I just updated the English document, please help review it, thanks.

**Review by kayx23 — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Review by pottekkat — APPROVED** [review]
Thank you.

**Pull request merged**
