### PR TITLE
fix: always parse domain when host is domain name

### PR DESCRIPTION
**Pull request by okaybase**
### Description

Plugin: traffic-split

Use a service-name as the host of weighted_upstreams's nodes, when redeploying the service (the pods ip changes), will result in the request 502.

image

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by leslie-tsang** [comment]
Hello there, need a test case to make sure it was fixed.

**Comment by okaybase** [comment]
> Hello there, need a test case to make sure it was fixed.

okay, i write the test case later, thanks ~

**Review by monkeyDluffy6017 — DISMISSED** [review]

**Comment by monkeyDluffy6017** [comment]
Try to merge the master branch

**Comment by okaybase** [comment]
> Try to merge the master branch

merged~

**Comment by okaybase** [comment]
> @okaybase please make the ci pass

okay, done~

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by soulbird — APPROVED** [review]

**Pull request merged**
