### PR TITLE
docs: updated Stream Proxy doc

### PR DESCRIPTION
**Pull request by kayx23**
### Description

Improved the part of doc before the MySQL example in Stream Proxy doc

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by kayx23** [comment]
@navendu-pottekkat @Neilblaze @moonming can any mod help with approval? Thx!

**Review by navendu-pottekkat — DISMISSED** [review]

**Comment by navendu-pottekkat** [comment]
@kayx23 Could you check the failing lint check? Ready to merge after that.

**Comment by kayx23** [comment]
@navendu-pottekkat sigh, my favourite thing to do, adding trailing spaces and failing CI checks! Should be good now. 

btw, I've noticed quite a few times that people are merging doc improvements PR into version specific branches which aren't carried over the main branch. This was resulted from directing using the "edit this page" button on the front end which automatically propose PR changes into a specific version (though you can select which branch to merge into but people dont usually notice). 

For my first doc PR I had to open a new PR to merge into the master branch. I subsequently discovered if you JUST merge the doc change into the master branch, the change isn't reflected in the most current version of doc (say 3.2). This _might_ result in people thinking the latest doc is still outdated and waste time fixing docs that are already fixed? 

Wonder what the suggested practice/workflow is here?

**Comment by navendu-pottekkat** [comment]
@kayx23 I guess it could be the delay between running updates to the apisix-website repo and updating this repo. Changes made here are only updated on the site when the apisix-website repo is built and published. The most recent changes are shown in the "next" version and not on the latest available version. When a new version of APISIX is released, the docs for it are also updated.

Does merging to version specific branches update the doc for that specific version? If yes, that might be the desired way it should work.

**Comment by kayx23** [comment]
> Does merging to version specific branches update the doc for that specific version? If yes, that might be the desired way it should work.

It does, but some of these changes are meant to be effective for subsequent releases and therefore, better be in master branch. I have left comments under all doc PRs merged into release 3.2 last time I noticed that look like they should be in master branch. Nobody seems to reply so far.

> next

ok understood

**Comment by kayx23** [comment]
@navendu-pottekkat please help with merging the change. Thanks!

**Comment by kayx23** [comment]
ready for review

**Review by Neilblaze — APPROVED** [review]
LGTM! 😃

**Review by navendu-pottekkat — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]
LGTM!

**Pull request merged**
