### PR TITLE
change: use 405 as the error code for unsupported HTTP method

### PR DESCRIPTION
**Pull request by spacewander**
### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible?

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
405 means Method Not Allowed, LGTM.

**Review by membphis — COMMENTED** [review]
missing test case

**Comment by spacewander** [comment]
@membphis 
There is one: https://github.com/apache/apisix/pull/2418/files#diff-71cab91a4d79fa23828f2cbf6ba02ff99f93d0109e4cc2b392253ffcf6d99889R304
I don't add test case to plugin_metadata as it will conflict with my another PR, and the case is trivial.

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
@spacewander got it, thx for your explain

**Comment by membphis** [comment]
merged, many thx ^_^

**Pull request merged**
