### PR TITLE
feat: switch resolver to lua-resty-dns-client

### LINKED ISSUE #2532: feat:   Apisix upstream domain resolver can not support "search  xxxx, options  xxxxx" in k8s environment
### Issue description
for example  in k8s environment , we can use  service name as backend nodes, sometime  for core DNS query we can combine the service name  and "svc.cluster.local" as the domain, the  resolve config is 
```
nameserver 10.96.0.10
search svc.cluster.local cluster.local
options ndots:5
```
apisix just support "nameserver",ref code:  https://github.com/apache/apisix/blob/master/apisix/core/utils.lua#L75,so we must define the full domain "xxxx.svc.cluster.local", But  we can not us other suffix such as "cluster.local". Should we support the full dns resolve rule?
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### PR DESCRIPTION
**Pull request by spacewander**
Fix #2532 
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by jenskeiner** [comment]
Hey, thanks for taking care of this DNS issue.

I've been bitten by this as well in a K8s environment where I want to refer to services just by their name w/o the full domain part which is environment-specific. Let me know in case I can help with anything. Otherwise, looking forward to seeing this merged to master. +1

**Comment by spacewander** [comment]
We are planning to release 2.3, so this PR will be merged later. There will be more DNS relative new features in the coming 2.4 version.
CC @gy09535

**Review by membphis — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Comment by gy09535** [comment]
> We are planning to release 2.3, so this PR will be merged later. There will be more DNS relative new features in the coming 2.4 version.
> CC @gy09535

good, got it.

**Comment by ShaoZeMing** [comment]
I found a problem. At present, after using this dns client, upstream services can implement dns search, but in plugins, when resty.http is used to generate requests, dns search cannot be implemented. Is there a way to deal with this?

**Comment by membphis** [comment]
@ShaoZeMing Welcome to create a new journal to discuss your questions. This PR has been merged, which means it is complete.

**Pull request merged**
