### PR TITLE
fix: the prometheus lables are inconsistent when using the same batch-processor instance on multi plugins

### PR DESCRIPTION
**Pull request by zhendongcmss**
fix https://github.com/apache/apisix/issues/6011

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by tzssangglass** [comment]
cc @spacewander what does patch-1 for? Do we need to fix the code on this branch?

**Review by spacewander — COMMENTED** [review]
I guess this PR is submitted to the wrong place?

**Comment by zhendongcmss** [comment]
> I guess this PR is submitted to the wrong place?

to 2.10.1.1 ?

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/issues/6011#issuecomment-1005334493

It looks like there's no problem on master so we don't need to fix it.

**Comment by zhendongcmss** [comment]
> ref: [#6011 (comment)](https://github.com/apache/apisix/issues/6011#issuecomment-1005334493)
> 
> It looks like there's no problem on master so we don't need to fix it.

But, 2.10.x is TLS version, I think it is necessary.

**Comment by tzssangglass** [comment]
> But, 2.10.x is TLS version, I think it is necessary.

We usually backport the bugfix from the master branch into the LTS version. if the bugfix is not found on master but exists on LTS verison, then it needs to be fixed. can you help to verify that this bug exists on the latest version of LTS:https://github.com/apache/apisix/tree/release/2.10?

**Comment by zhendongcmss** [comment]
> > But, 2.10.x is TLS version, I think it is necessary.
> 
> We usually backport the bugfix from the master branch into the LTS version. if the bugfix is not found on master but exists on LTS verison, then it needs to be fixed. can you help to verify that this bug exists on the latest version of LTS:https://github.com/apache/apisix/tree/release/2.10?

I am sure that 2.10 has this bug.

**Comment by tzssangglass** [comment]
Can add a test case to reproduce this on 2.10?

**Comment by zhendongcmss** [comment]
> Can add a test case to reproduce this on 2.10?

ＮＰ．ａｄｄ　ｔｅｓｔ　ｃａｓｅ　ｏｎ　ｔｈｉｓ　ＰＲ　ｏｒ　ｅｌｓｅｗｈｅｒｅ　？

**Comment by tzssangglass** [comment]
> > Can add a test case to reproduce this on 2.10?
> 
> ＮＰ．ａｄｄ　ｔｅｓｔ　ｃａｓｅ　ｏｎ　ｔｈｉｓ　ＰＲ　ｏｒ　ｅｌｓｅｗｈｅｒｅ　？

you need to submit a new PR to release/2.10 branch.

**Pull request closed without merging**
