### PR TITLE
feat: add method and status attr in prometheus

### PR DESCRIPTION
**Pull request by hugoray**
add method and status attr in prometheus

### Description

add method and status attribute in prometheus module

Fixes # (issue)

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Why we need this?

**Comment by hugoray** [comment]
It fixes the prometheus labels inconsistency problem.

**Comment by monkeyDluffy6017** [comment]
Could you explain the problem more clearly?

**Comment by hugoray** [comment]
In promethus, we often need to specify the request type and the http_ret/status of one HTTP request.  By adding this two attributes,  the dashboard could draw new histogram based on them.

**Comment by monkeyDluffy6017** [comment]
Maybe you could keep this in your own project? The metrics that each user cares about vary, and there's no way we can include all of them

**Comment by hugoray** [comment]
I do think the change of metrics can help people get the accurate message of HTTP request, no matter the scene who use, need to get these two attributes when using prometheus.

**Comment by nic-chen** [comment]
hi @hugoray 

There are enough metrics and metrics labels currently exposed, and some users have performance problems due to excessive data volume during use. 

I think the better solution is to customize the required metrics and labels by configuration of the prometheus plugin. Would you like to contribute this feature?

**Comment by monkeyDluffy6017** [comment]
I will close this pr, feel free to reopen it

**Pull request closed without merging**
