### PR TITLE
fix: serverless plugin not work in header_filter phase

### PR DESCRIPTION
**Pull request by mddmzl**
### What this PR does / why we need it:
fix spelling error of header_filter, which couse serverless not work in header_filter phase

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Comment by moonming** [comment]
@mddmzl good catch 👍 
please fix https://github.com/apache/apisix/blob/master/t/admin/schema.t#L160 and https://github.com/apache/apisix/blob/master/t/admin/schema.t#L200 too, thx

**Comment by mddmzl** [comment]
@moonming should i squash the two commits into one and create a new pull request?

**Comment by moonming** [comment]
No, just commit in the same PR. I will squash commits before merge.

**Comment by mddmzl** [comment]
@moonming

**Comment by moonming** [comment]
@mddmzl please fix https://github.com/apache/apisix/blob/784789f3e8b580407eee5abc27ce376372f4241d/apisix/plugins/serverless.lua#L32 too, thanks.

**Comment by mddmzl** [comment]
@moonming It's OK now.

**Review by moonming — APPROVED** [review]

**Comment by moonming** [comment]
@mddmzl thx, merged

**Pull request merged**
