### PR TITLE
docs: update the architecture diagram

### PR DESCRIPTION
**Pull request by iamayushdas**
### What this PR does / why we need it:
Updated the architecture - admin API replaced with Manager API
[#307](https://github.com/apache/apisix-website/issues/307) from apisix-website

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by iamayushdas** [comment]
@juzhiyuan conflicts removed

**Comment by iamayushdas** [comment]
@juzhiyuan @Yiyiyimu @membphis can i have a review?

**Comment by Yiyiyimu** [comment]
Do you mind attaching a screenshot of new image on APISIX website 😀

**Comment by iamayushdas** [comment]
> Do you mind attaching a screenshot of new image on APISIX website 😀 

Okay, On it

**Comment by moonming** [comment]
We are still using admin API in this repo, and manager API is using in the apisix-dashboard repo.

**Comment by membphis** [comment]
I think you need to submit a PR to https://github.com/apache/apisix-website

The new image link: https://raw.githubusercontent.com/apache/apisix-dashboard/master/docs/assets/images/architecture.png

**Comment by membphis** [comment]
So I think we can close this PR

**Comment by iamayushdas** [comment]
> So I think we can close this PR

okay got youu now

**Comment by iamayushdas** [comment]
> We are still using admin API in this repo, and manager API is using in the apisix-dashboard repo.

yeah this is exactly where i was confused

**Pull request closed without merging**
