### PR TITLE
add global name

### LINKED ISSUE #1379: feature: add global name
APISIX need add global name for log platform, zipkin, such as spring boot 'spring.application.name',

### PR DESCRIPTION
**Pull request by qiujiayu**
### Issues resolved

Fix #1379

### CODE REVIEW

**Comment by membphis** [comment]
In Apache APISIX, how about allowing users to customize global variables to solve such problems?

```
global_name = xxxx
```

then we can reference it in the plugin, that is an example:

```
{
    ....
    "name": "$$global_name"
}
```

**Comment by qiujiayu** [comment]
> In Apache APISIX, how about allowing users to customize global variables to solve such problems?
> 
> ```
> global_name = xxxx
> ```
> 
> then we can reference it in the plugin, that is an example:
> 
> ```
> {
>     ....
>     "name": "$$global_name"
> }
> ```

The following configuration needs to be added for the use:

```
 {
     ....
     "name": "$$global_name"
 }
```

That will not be able to simplify the configuration.

那就达不到简化配置的效果。

**Comment by membphis** [comment]
I'm sorry to reply so late, I'm hesitant to add a similar function. Hope to hear more opinions from others.

**Comment by qiujiayu** [comment]
> I'm sorry to reply so late, I'm hesitant to add a similar function. Hope to hear more opinions from others.

@lilien1010  @juzhiyuan @wu-sheng @moonming 

What do you think about this?

**Pull request closed without merging**
