### PR TITLE
fix: support grpc proxy with upstream_id support

### PR DESCRIPTION
**Pull request by yongboy**
We need the grpc proxy with `upstream_id` support as the http proxy handle way ...

1. Add local function `load_upstream_by_id` for loading one upstream from ETCD
2. Add `grpc_access_phase` with `upstream_id` support
3. Refactoring the load one upstream function within `http_access_phase` & `grpc_access_phase` functions called

:))

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by spacewander** [comment]
I think there is a simple way to solve it. You can take a look at the `apisix/init.lua` and `rockspec/apisix-master-0.rockspec` in https://github.com/apache/apisix/pull/3224/files.

**Comment by yongboy** [comment]
@spacewander 
I don't quite follow your point of view. 

If you have a good way, please supply a patch for apisix 2.1/2.2 users.

The apisix 2.*'s grpc access should like the Apisix 1.5’s handle way with the upstream_id support in my online environment, we manage the grpc's upstream as the http apis's upsreams in apisix-dashboard, so we need it.

PS:

I don't know how to fix the below error, maybe I need your help.

```
Error: [error] init_by_lua error: /home/runner/work/apisix/apisix/apisix/core.lua:21: failed to parse yaml config: failed to merge, path[apisix->node_listen] expect: number, but got: string
stack traceback:
	[C]: in function 'error'
	/home/runner/work/apisix/apisix/apisix/core.lua:21: in main chunk
	[C]: in function 'require'
	/home/runner/work/apisix/apisix/apisix/init.lua:18: in main chunk
	[C]: in function 'require'
	init_by_lua:9: in main chunk
t/core/config-default.t ................... ok
```

**Comment by moonming** [comment]
> I think there is a simple way to solve it. You can take a look at the `apisix/init.lua` and `rockspec/apisix-master-0.rockspec` in https://github.com/apache/apisix/pull/3224/files.

The PR of dubbo is relatively large, it would be better if you can directly tell the solution @spacewander

**Comment by moonming** [comment]
@nic-chen please take a look

**Comment by nic-chen** [comment]
@yongboy 

I think the key points are:
https://github.com/apache/apisix/pull/3224/files#diff-7439ffe94cc4bcad12066d5d83f6c1004b8e9b3ff5097b645fa7c700eb3b3743R26-R559

https://github.com/apache/apisix/pull/3224/files#diff-c6a774885b1f6ef5f4cb5d027eb59cf81d6065588e3e7c5620814b3d0819ec1eR61


We don't need to maintain `access_phase` function for each protocol, we only need to call the corresponding additional function as needed at the end of `http_access_phase`.

**Comment by spacewander** [comment]
I have discussed with @yongboy 
It seems he will wait for our version of fix.

**Comment by nic-chen** [comment]
> I have discussed with @yongboy
> It seems he will wait for our version of fix.

OK.

**Pull request closed without merging**
