### PR TITLE
docs: Update incorrect uri in expose-api.md

### LINKED ISSUE #9182: docs: incorrect uri in "expose-api" tutorial
It should be `/anything` and `example.com` here.

_Originally posted by @juzhiyuan in https://github.com/apache/apisix/pull/7952#discussion_r1150118134_

### PR DESCRIPTION
**Pull request by woyouyitouchenfeijv**
Resolves #9182

### CODE REVIEW

**Review by kingluo — APPROVED** [review]

**Comment by Neilblaze** [comment]
Duplicate of #8730

**Comment by woyouyitouchenfeijv** [comment]
update expose-api.md ,use `/anything` and `example.com`

**Review by woyouyitouchenfeijv — COMMENTED** [review]
update get to anything 
Because the example uses anything

**Comment by woyouyitouchenfeijv** [comment]
> Duplicate of #8730

soorry ， I also think yours is better  ，This question is very simple. I want to try it for the first time

**Comment by monkeyDluffy6017** [comment]
Hi @woyouyitouchenfeijv, please solve the conflicts

**Comment by monkeyDluffy6017** [comment]
considered resolved

**Pull request closed without merging**
