### PR TITLE
ci(apisix test): grep search [error] from file error.log

### PR DESCRIPTION
**Pull request by kwanhur**
### What this PR does / why we need it:

grep search `[error]` from `logs/error.log` file instead of `cat logs/error.log` stdin

- reduce one command operation

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Review by tzssangglass — DISMISSED** [review]

**Comment by spacewander** [comment]
@kwanhur 
When you resolve the shellcheck warnings, could you submit all of them together, instead of one type per PR?

**Comment by spacewander** [comment]
Maybe we should set up a CI to lint all the shell scripts.

**Review by spacewander — CHANGES_REQUESTED** [review]
Don't merge until we have agreed on a framework (for example, a linter in the CI) to handle all the shellcheck warnings instead of handling them one by one.

**Comment by kwanhur** [comment]
> @kwanhur When you resolve the shellcheck warnings, could you submit all of them together, instead of one type per PR?

ok, I try to do batch processing.

**Comment by kwanhur** [comment]
> @kwanhur When you resolve the shellcheck warnings, could you submit all of them together, instead of one type per PR?

I'll drop shellcheck directive here, shellcheck ci linter place in #6331

**Comment by kwanhur** [comment]
> Maybe we should set up a CI to lint all the shell scripts.

Another PR #6428 to do this.

**Comment by tzssangglass** [comment]
@kwanhur Is it possible to close this PR?

**Comment by kwanhur** [comment]
> @kwanhur Is it possible to close this PR?

Just wait one moment, after https://github.com/apache/apisix/pull/6428#issuecomment-1050550756 confirmation.

**Comment by kwanhur** [comment]
This one had been merged into #6428

**Pull request closed without merging**
