### PR TITLE
improve: use optimistic locking to avoid concurrency problem in admin…

### PR DESCRIPTION
**Pull request by tokers**
### What this PR does / why we need it:

There is a potential concurrency problem in all admin PATCH APIs when
two patch requests come in simultaneously, in such case, the patched
result of the first applied request will be overridden, although the
probability is tiny, from the perspective of software's robustness,
that's not what we wanna see.

In this commit, we use the optimistic locking to avoid this problem, for
the example aforementioned, the second PATCH request will failure, and
it's up to the user to retry this PATCH request again.

The optimistic locking mechanism in ETCD v2 APIs is showed by arg
`prevIndex`.

Signed-off-by: tokers <zchao1995@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by membphis — APPROVED** [review]
nice PR

**Comment by tokers** [comment]
@membphis :)

**Review by moonming — APPROVED** [review]

**Comment by tokers** [comment]
@membphis @moonming This PR should be adjusted to the ETCD v3 data structure, So i mark it as work in progress.

**Comment by membphis** [comment]
@tokers got it, we can merge this PR later

**Comment by tokers** [comment]
@membphis Adjusted.

**Comment by tokers** [comment]
@membphis @moonming Please help me to retry the checks 😂, it's weird that this failure only in linux_tengine.

**Comment by tokers** [comment]
@membphis Could you review this PR once again? The adjustment was done.

**Pull request merged**
