### PR TITLE
chore: update ngxin-lua-prometheus verison

### LINKED ISSUE #5755: [DISCUSS]: Improving the performance of the prometheus plugin
### Issue description

the community has recently received reports from users of APISIX generating long-tail requests. e.g.
https://github.com/apache/apisix/issues/5604
https://github.com/apache/apisix/issues/5500

Talking to them and testing on their environment, we found the problem that when starting the prometheus plugin on APISIX, the prometheus service when collecting data (accessing /apisix/prometheus/metrics) causes APISIX to delay some of the requests, i.e. long-tail requests.

According to my analysis, this is because the collect function is computationally heavy and takes up too many CPU time slices.

https://github.com/apache/apisix/blob/5ae38f81f25fc58a040e30d12ba8fef33bb56f60/apisix/plugins/prometheus/exporter.lua#L281-L289

I have tried to do some optimisation, which has worked, but not as well as I would have liked.

here are my optimizations

```diff
diff --git a/apisix/plugins/prometheus/exporter.lua b/apisix/plugins/prometheus/exporter.lua
index d565b4c4..32f51ddb 100644
--- a/apisix/plugins/prometheus/exporter.lua
+++ b/apisix/plugins/prometheus/exporter.lua
@@ -34,7 +34,7 @@ local get_stream_routes = router.stream_routes
 local get_protos = require("apisix.plugins.grpc-transcode.proto").protos
 local service_fetch = require("apisix.http.service").get
 local latency_details = require("apisix.utils.log-util").latency_details_in_ms
-
+local ngx_sleep = ngx.sleep
 
 
 -- Default set of latency buckets, 1ms to 60s:
@@ -174,17 +174,18 @@ local function nginx_status()
         core.log.error("failed to fetch Nginx status")
         return
     end
-
     -- Active connections: 2
     -- server accepts handled requests
     --   26 26 84
     -- Reading: 0 Writing: 1 Waiting: 1
 
+    ngx_sleep(0)
     local iterator, err = re_gmatch(res.body, [[(\d+)]], "jmo")
     if not iterator then
         core.log.error("failed to re.gmatch Nginx status: ", err)
         return
     end
+    ngx_sleep(0)
 
     for _, name in ipairs(ngx_status_items) do
         local val = iterator()
@@ -196,6 +197,7 @@ local function nginx_status()
         metrics.connections:set(val[0], label_values)
 
     end
+    ngx_sleep(0)
 end
 
 
@@ -216,7 +218,7 @@ local function set_modify_index(key, items, items_ver, global_max_index)
 
     key_values[1] = key
     metrics.etcd_modify_indexes:set(max_idx, key_values)
-
+    ngx_sleep(0)
 
     global_max_index = max_idx > global_max_index and max_idx or global_max_index
 
@@ -231,19 +233,19 @@ local function etcd_modify_index()
     -- routes
     local routes, routes_ver = get_routes()
     global_max_idx = set_modify_index("routes", routes, routes_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- services
     local services, services_ver = get_services()
     global_max_idx = set_modify_index("services", services, services_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- ssls
     local ssls, ssls_ver = get_ssls()
     global_max_idx = set_modify_index("ssls", ssls, ssls_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- consumers
     local consumers, consumers_ver = get_consumers()
     global_max_idx = set_modify_index("consumers", consumers, consumers_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- global_rules
     local global_rules = router.global_rules
     if global_rules then
@@ -253,28 +255,29 @@ local function etcd_modify_index()
         -- prev_index
         key_values[1] = "prev_index"
         metrics.etcd_modify_indexes:set(global_rules.prev_index, key_values)
-
+        ngx_sleep(0)
     else
         global_max_idx = set_modify_index("global_rules", nil, nil, global_max_idx)
+        ngx_sleep(0)
     end
 
     -- upstreams
     local upstreams, upstreams_ver = get_upstreams()
     global_max_idx = set_modify_index("upstreams", upstreams, upstreams_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- stream_routes
     local stream_routes, stream_routes_ver = get_stream_routes()
     global_max_idx = set_modify_index("stream_routes", stream_routes,
         stream_routes_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- proto
     local protos, protos_ver = get_protos()
     global_max_idx = set_modify_index("protos", protos, protos_ver, global_max_idx)
-
+    ngx_sleep(0)
     -- global max
     key_values[1] = "max_modify_index"
     metrics.etcd_modify_indexes:set(global_max_idx, key_values)
-
+    ngx_sleep(0)
 end
 
 
@@ -297,15 +300,17 @@ function _M.collect()
     if config.type == "etcd" then
         -- etcd modify index
         etcd_modify_index()
-
+        ngx_sleep(0)
         local version, err = config:server_version()
         if version then
             metrics.etcd_reachable:set(1)
+            ngx_sleep(0)
 
         else
             metrics.etcd_reachable:set(0)
             core.log.error("prometheus: failed to reach config server while ",
                            "processing metrics endpoint: ", err)
+            ngx_sleep(0)
         end
 
         -- Because request any key from etcd will return the "X-Etcd-Index".
@@ -317,13 +322,17 @@ function _M.collect()
             -- global max
             key_values[1] = "x_etcd_index"
             metrics.etcd_modify_indexes:set(res.headers["X-Etcd-Index"], key_values)
+            ngx_sleep(0)
         end
     end
 
     metrics.node_info:set(1, gen_arr(hostname))
+    ngx_sleep(0)
 
     core.response.set_header("content_type", "text/plain")
-    return 200, core.table.concat(prometheus:metric_data())
+    local metric_data = prometheus:metric_data()
+    ngx_sleep(0)
+    return 200, core.table.concat(metric_data)
 end
 
 

```

and I've done some local verification

****config****

1. upstream server is an openresty, the nginx.conf is https://github.com/apache/apisix/tree/master/benchmark/server/conf

2. the route config is

```shell
curl --location --request PUT 'http://127.0.0.1:9080/apisix/admin/routes/1' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "plugins": {
        "prometheus":{}
    },
    "upstream": {
        "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin"
    },
    "uri": "/get"
}'
```

3. the config.yaml is 

```yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
nginx_config:
  http:
    enable_access_log: false
  worker_processes: 1
```

****test****

1. no prometheus plugin

```shell
wrk2 -t4 -c200 -d60s -R5000 --u_latency http://127.0.0.1:9080/get
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%  669.00us
 75.000%    0.97ms
 90.000%    1.30ms
 99.000%   10.90ms
 99.900%   39.55ms
 99.990%   45.69ms
 99.999%   49.44ms
100.000%   49.47ms
```

2. with prometheus plugin

use wrk to trigger prometheus clooect data

```shell
wrk2 -t4 -c100 -d6000s -R200 --u_latency http://127.0.0.1:9091/apisix/prometheus/metrics
```

test

```shell
wrk2 -t4 -c200 -d60s -R5000 --u_latency http://127.0.0.1:9080/get
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%    2.23ms
 75.000%   13.78ms
 90.000%   28.03ms
 99.000%   46.59ms
 99.900%   64.54ms
 99.990%   90.69ms
 99.999%   99.71ms
100.000%  101.57ms
``` 

3. with prometheus plugin and optimise

the trigger is as above

test

```shell
wrk2 -t4 -c200 -d60s -R5000 --u_latency http://127.0.0.1:9080/get
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%    3.93ms
 75.000%    7.65ms
 90.000%   14.16ms
 99.000%   33.85ms
 99.900%   51.65ms
 99.990%   60.06ms
 99.999%   68.42ms
100.000%   68.48ms
```

for more information on how to optimise, refer to: https://groups.google.com/g/openresty/c/fuY_vTS01eg

when collecting data in prometheus, we use `nix.timer(0)` to give up CPU time slice to give epoll a chance to process more requests.

based on the above optimisation ideas we can assume that this optimisation is effective.

but we need to make more optimizations to the peometheus plugin, or even modify lua-resty-prometheus.

thanks @jagerzhang @sandy420

would you like to improve this optimization?

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### PR DESCRIPTION
**Pull request by tzssangglass**
Closes #5755

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

The following is a simple test

prepare

1. add prometheus plugin

```shell
curl -i http://127.0.0.1:9080/apisix/adminglobal_rules/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "plugins": {
        "prometheus": {}
    }
}'
```

2. add rouet

```shell
curl -i http://127.0.0.1:9080/apisix/adminroutes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "upstream": {
        "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin"
    },
    "uri": "/hello"
}'
```

3. wrk2

```shell
# mock client request
wrk -t4 -c100 -d90s -R5000 --u_latency http://127.0.0.1:9080/hello

# mock prometheus  collection
wrk -t4 -c100 -d100s -R10 --u_latency http://127.0.0.1:9091/apisix/prometheus/metrics
```

#### before update prometheus version:

*request latency*

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%  415.00us
 75.000%  594.00us
 90.000%    0.87ms
 99.000%    4.95ms
 99.900%   17.26ms
 99.990%   33.53ms
 99.999%   40.96ms
100.000%   46.69ms
```

*prometheus latency*

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%    9.73ms
 75.000%   17.36ms
 90.000%   27.34ms
 99.000%   38.85ms
 99.900%   41.50ms
 99.990%   43.49ms
 99.999%   43.49ms
100.000%   43.49ms
```

flamegraph 
origin_flame

#### after update prometheus version:

*request latency*

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%  605.00us
 75.000%    0.89ms
 90.000%    1.26ms
 99.000%    2.58ms
 99.900%    9.80ms
 99.990%   14.20ms
 99.999%   18.74ms
100.000%   19.65ms
```

*prometheus latency*

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%    1.67ms
 75.000%    2.10ms
 90.000%    2.86ms
 99.000%    6.89ms
 99.900%   10.61ms
 99.990%   10.67ms
 99.999%   10.67ms
100.000%   10.67ms
```

flamegraph 
update_flame

We can assume that the impact on request latency when prometheus collects information is significantly reduced after the update.

#### why not use `ngx.timer(0)`

From the flamegraph, the code in the prometheus plugin does not significantly increase latency, which is most noticeable in the `fix_histogram_bucket_labels` function of nginx-lua-prometheus, even if this function is optimized.

The main delay is due to the regular matching in this function.

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Comment by xianshun163** [comment]
@tzssangglass  I use the apisix 1.11.0, Do you know   how can I   fix the issue?

**Comment by tzssangglass** [comment]
> @tzssangglass I use the apisix 1.11.0, Do you know how can I fix the issue?

Unfortunately this version is too old, we don't maintain this version, you can consider upgrading, this month we will release a new LTS version -> 2.13.0.

**Comment by xianshun163** [comment]
@tzssangglass   sorry , I made a mistake. My version is  2.11.0

**Comment by xianshun163** [comment]
I deploy it like this:  this is my docker file: 
FROM apache/apisix:2.11.0-alpine
MAINTAINER xs
COPY ./plugins/*.lua  /usr/local/apisix/apisix/plugins/
COPY ./discovery/*.lua      /usr/local/apisix/apisix/discovery/
COPY ./config/*.yaml   		  /usr/local/apisix/conf/

and then I got my own docker  image,  I deploy it in the k8s.

**Comment by tzssangglass** [comment]
> I deploy it like this: this is my docker file: FROM apache/apisix:2.11.0-alpine MAINTAINER xs COPY ./plugins/_.lua /usr/local/apisix/apisix/plugins/ COPY ./discovery/_.lua /usr/local/apisix/apisix/discovery/ COPY ./config/*.yaml /usr/local/apisix/conf/
> 
> and then I got my own docker image, I deploy it in the k8s.

Can you wait for the LTS version to be released? Because this PR change is only for the master branch. Rebuilding the image after the next release will affect the dependencies in the image.

**Comment by xianshun163** [comment]
@tzssangglass ,  I  have see the commit, it  is only change this file:  apisix-master-0.rockspec, 
    -  "nginx-lua-prometheus = 0.20210206",
  + "nginx-lua-prometheus = 0.20220127",
  
I'm not sure if I modified this file like above. Will the apisix  get the new version of the dependency when  it  starting?

**Comment by xianshun163** [comment]
When the new version was just released, I didn't dare to use it directly. I prefer to fix the bug manually first.

**Comment by tzssangglass** [comment]
> I'm not sure if I modified this file like above. Will the apisix get the new version of the dependency when it starting?

Of course not.

**Comment by xianshun163** [comment]
> > I'm not sure if I modified this file like above. Will the apisix get the new version of the dependency when it starting?
> 
> Of course not.

image

I get the dockerfile: https://github.com/apache/apisix-docker/edit/release/apisix-2.11.0/alpine/Dockerfile
 modify  the deps:    "nginx-lua-prometheus = 0.20220127",
and build the images in local. 

it is update now.

**Comment by xianshun163** [comment]
@tzssangglass ，I have updated the version of nginx-lua-prometheus  dependency package. I directly used the new version of dependency package when packaging with  dockerfile. 
My version of apifix is 2.11.0.
 As shown in the figure. I found that the apifix delay on grafana is not stable, as shown  in the figure. At the beginning, it is 190ms, and then it becomes more than 1s.

And, looking at the graph of grafana, the delay is still relatively large.

image


企业微信截图_16473447444294

**Comment by tzssangglass** [comment]
> @tzssangglass ，I have updated the version of nginx-lua-prometheus dependency package. I directly used the new version of dependency package when packaging with dockerfile. My version of apifix is 2.11.0. As shown in the figure. I found that the apifix delay on grafana is not stable, as shown in the figure. At the beginning, it is 190ms, and then it becomes more than 1s.
> 
> And, looking at the graph of grafana, the delay is still relatively large. I just piloted a few services. The QPS is less than 100, and the CPU utilization of the gateway is also very low.
> 
> image
> 
> 企业微信截图_16473447444294
> 
> the access.log of the nginx print the variable below: $request_time $upstream_connect_time $upstream_response_time in the access.log , I can not find the record who has so manay delay time.

Building your own image is a black box for us developers (even if you say how you built it, we still don't have access to its details)

Now that the apisix-dev image builds the master branch once a day and pushes it to Docker Hub, can you use this image to verify the problem?

ref: https://hub.docker.com/r/apache/apisix/tags?page=1&name=dev

**Comment by xianshun163** [comment]
I got it  in this issue:  #6029

**Pull request merged**
