### PR TITLE
Support SSL verify option to Authz Keycloak plugin

### LINKED ISSUE #1855: Support verify ssl option parameter in Keycloak Plugin
When Keycloak is deployed in an HTTPs environment the Keycloak plugin fails to resolve SSL certs with the following error:

```
lua ssl certificate verify error: (20: unable to get local issuer certificate),
```
To resolve this problem either the Nginx should have the following configurations

```
lua_ssl_verify_depth 2;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
```

**OR**
configure SSL verify to `false` while making the HTTP call to Keycloak server

### PR DESCRIPTION
**Pull request by sshniro**
Fix #1855

### CODE REVIEW

**Comment by membphis** [comment]
need test case

**Comment by sshniro** [comment]
Hi, @membphis I'm not sure how to write a test case for this. This param is available via the httpc library itself and to expose keycloak via https we need to have additional setup in CI/CD pipleline. Furthermore, the OpenID connect plugin also supports a similar parameter.

The following shows an open ID connect plugin configuration, and it also internally uses this parameter: `ssl_verify`
Screenshot 2020-08-03 at 20 11 07

**Comment by membphis** [comment]
https://github.com/nic-chen/apisix/blob/script/t/plugin/jwt-auth.t#L56

I am not sure if this example is enough for you.

**Comment by sshniro** [comment]
@membphis thanks, I was able to expose Keyclaok via https port and check for this configuration.

**Comment by sshniro** [comment]
@membphis can we merge this PR?

**Comment by membphis** [comment]
@sshniro yes, merged already

**Comment by sshniro** [comment]
Thanks.

**Pull request merged**
