### PR TITLE
test: add shell script for run APISIX testcases on ARM64

### PR DESCRIPTION
**Pull request by idbeta**
### What this PR does / why we need it:
add shell script for run APISIX testcases on ARM64

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by imjoey** [comment]
@idbeta Hi, may I ask that is there any plan to support CI at ARM64 platform? It seems that we need to provide a self-hosted ARM64 runner to integrate GitHub Action. Looking forward to your insights. Thanks.

**Comment by idbeta** [comment]
> may I ask that is there any plan to support CI at ARM64 platform? It seems that we need to provide a self-hosted ARM64 runner to integrate GitHub Action. Looking forward to your insights. Thanks.

 It seems that we need to provide a self-hosted ARM64 runner to integrate GitHub Action. —— yes, agree with you, I didn't find another way.
may I ask that is there any plan to support CI at ARM64 platform? —— I have discussed with @membphis , it is not suitable for Apache project to use self-hosted method for CI testing, so it is good to provide manual testing script first.

**Comment by imjoey** [comment]
> —— I have talked with @membphis , it is not suitable for Apache project to use self-hosted method for CI testing, so it is good to provide manual testing script first.

@idbeta Huawei is working on donating ARM CI resources to various open source community to leverage the ARM ecosystem. AFAIK, Apache Flink and Apache Kudu are both using the ARM virtual machines provisioned by [OpenLab Testing](https://openlabtesting.org) for ARM CI. So I could ask OpenLab for helping us delivering the ARM CI and version releases.

**Comment by idbeta** [comment]
> @idbeta Huawei is working on donating ARM CI resources to various open source community to leverage the ARM ecosystem. AFAIK, Apache Flink and Apache Kudu are both using the ARM virtual machines provisioned by [OpenLab Testing](https://openlabtesting.org) for ARM CI. So I could ask OpenLab for helping us delivering the ARM CI and version releases.

That  is great, i am looking forward to it, thank you. If want to run CI completely under ARM64, need to solve another problem that many CI-dependent docker images do not have an ARM64 version.
>grpc_server_example —— no, we are working on it
redis —— no
mendhak/http-https-echo —— no
sshniro/keycloak-apisix —— no
bitnami/zookeeper —— no
bitnami/kafka —— yes，ligato/kafka-arm64
bitinit/eureka —— no
apache/skywalking-oap-server —— no

**Comment by imjoey** [comment]
> That is great, thank you. If want to run CI completely under ARM64, need to solve another problem is many CI-dependent docker images do not have an ARM64 version.
> 
> > grpc_server_example —— no, we are working on it
> > redis —— no

@idbeta we have built two redis 5.x of images under ARM64 architecture, for Kunpeng-920 and for FT-2000 each. Where do you locate the images in? I'm happy to upload them if needed.

> > mendhak/http-https-echo —— no
> > sshniro/keycloak-apisix —— no
> > bitnami/zookeeper —— no
> > bitnami/kafka —— yes，ligato/kafka-arm64
> > bitinit/eureka —— no
> > apache/skywalking-oap-server —— no

@idbeta yep, this indeed is a tough problem. openEuler community is dedicating to the ARM64 docker images of various applications. I would keep an eye on it. Meanwhile, we could compile them locally.

**Comment by imjoey** [comment]
@idbeta Just FYI, for redis 5.x ARM64 image, simply run `docker pull isrc.iscas.ac.cn/oepkgs/kubernetes/library/redis:5.0.5-alpine` to fetch the pre-built image. Noted that it's only for Kunpeng-920.

**Comment by idbeta** [comment]
> @idbeta we have built two redis 5.x of images under ARM64 architecture, for Kunpeng-920 and for FT-2000 each. Where do you locate the images in? I'm happy to upload them if needed.

I locate the images in https://hub.docker.com/, thank you so much.

**Review by moonming — CHANGES_REQUESTED** [review]
why not use dockerfile for it？

**Comment by idbeta** [comment]
> why not use dockerfile for it？

This script is just a preliminary idea for the backup, not the final solution. If want to fully implement it, need to solve the problems mentioned above: 1, self-hosted;  2, CI-dependent docker images.

**Comment by idbeta** [comment]
> > —— I have talked with @membphis , it is not suitable for Apache project to use self-hosted method for CI testing, so it is good to provide manual testing script first.
> 
> @idbeta Huawei is working on donating ARM CI resources to various open source community to leverage the ARM ecosystem. AFAIK, Apache Flink and Apache Kudu are both using the ARM virtual machines provisioned by [OpenLab Testing](https://openlabtesting.org) for ARM CI. So I could ask OpenLab for helping us delivering the ARM CI and version releases.

After checking Apache's official documentation, I found that although Apache allows using self-hosted for testing, it is not recommended. https://infra.apache.org/self-hosted-runners.html
I went to `openlabtesting.org` to check it out, `http://status.openlabtesting.org/status` prompt `Something went wrong.` How to make APISIX perform ARM64 tests on it?

**Pull request closed without merging**
