### PR TITLE
etcd can use  etcd.debug = true open etcd debug info

### PR DESCRIPTION
**Pull request by dino-ma**
https://github.com/apache/apisix/issues/3242

etcd can use  etcd.debug = true open etcd debug info

### CODE REVIEW

**Comment by spacewander** [comment]
Personally I prefer using `argparse` to parse a command line option instead of adding new entry in the yaml file.

**Comment by dino-ma** [comment]
> Personally I prefer using `argparse` to parse a command line option instead of adding new entry in the yaml file.

ok .I'll give it a try

**Comment by Firstsawyou** [comment]
add a semantic PR title, please see here: [https://github.com/zeke/semantic-pull-requests ](https://github.com/zeke/semantic-pull-requests)
By the way, the CI error needs to be resolved.

**Comment by Yiyiyimu** [comment]
> > Personally I prefer using `argparse` to parse a command line option instead of adding new entry in the yaml file.
> 
> ok .I'll give it a try

Hi @dino-ma, if you encounter some obstacles, you could take [code](https://github.com/apache/apisix/pull/2101/files#diff-228a51571b53709ad043d1c6c14fc8e508c248a84f8014fe548b5d259cedd5ddR411-R415) #2101 as a reference

**Pull request closed without merging**
