### PR TITLE
docs: Make tutorials section

### LINKED ISSUE #7854: docs: Add How-to-guides section to APISIX Website API Gateway
### Current State

Currently, we have categorization based on plugins but there is no separation by usability cases.

Actually, plugins cover many things but It is hard to navigate through an exact fit plugin for some use cases without opening the individual plugin tutorial.

For newbies will be quite challenging to understand the core use cases of API Gateway.

### Desired State

We should have a How-to-guides section with learning content per each API Gateway use case that includes the following subpages:

Expose APIs
Protect APIs
Secure API
Monitor APIs
Improve performance. 
Health Check.
Add multiple versions. 
Cache API responses. 
Mock API responses.
Canary release. 
.... more

We have already enough blog posts that cover many API Gateway use cases we can rewrite them for each how-to guide page.

Here is the link to issue #6461

https://github.com/apache/apisix/issues/6461

You can see examples for Azure API Management or Kong API Gateway how the content is structured:

image

image

### PR DESCRIPTION
**Pull request by Boburmirzo**
### Description

Converted How-to guides section to Tutorials because our content is **learning-oriented** to help the developers acquire basic competence.

Please refer to this guide to understand the difference:

https://diataxis.fr/tutorials-how-to/

@LiteSun @hf400159 @SylviaBABY and @juzhiyuan 

Fixes #7854 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by SylviaBABY — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by hf400159 — APPROVED** [review]

**Comment by Boburmirzo** [comment]
now finally we are good to go:))

**Comment by juzhiyuan** [comment]
> now finally we are good to go:))

Hi @Boburmirzo, can you check the error please?

**Comment by Boburmirzo** [comment]
> > now finally we are good to go:))
> 
> Hi @Boburmirzo, can you check the error please?

Which error do you mean?

**Comment by juzhiyuan** [comment]
@Boburmirzo I use GitHub App just now 😅 It shows there have some title errors. But the web version looks good.

**Comment by Boburmirzo** [comment]
> @Boburmirzo I use GitHub App just now 😅 It shows there have some title errors. But the web version looks good.

@juzhiyuan I had also similar issue today.

**Pull request merged**
