### PR TITLE
fix(prometheus): don't provide etcd metrics when you don't use it

### PR DESCRIPTION
**Pull request by spacewander**
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible?

### CODE REVIEW

**Comment by spacewander** [comment]
Here is the backtrace of error.log when you try to access the prometheus path and config center is not etcd:
```
.../incubator-apisix/apisix/plugins/prometheus/exporter.lua:298: attempt to call method 'getkey' (a nil value)
```

**Comment by idbeta** [comment]
@spacewander is it about #2394 ?

**Comment by spacewander** [comment]
@idbeta 
Look like they are two difference issue.

**Comment by idbeta** [comment]
@spacewander I see.

**Review by membphis — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
