### PR TITLE
feat: add option to include request body and response body in log util

### LINKED ISSUE #10803: feat: Add schema attribute definition for some log plug-ins
### Description

The PR submitted before was #10738, dealing with the problem of #9190 .

Some plug-in related attributes need to be improved, such as include_req_body, include_req_body_expr, include_resp_body, include_resp_body_expr

Current status：

The list of plugins with missing attributes is as follows： 

- skywalking-logger
- tcp-logger
- udp-logger
- syslog
- sls-logger
- elasticsearch-logger
- splunk-hec-logging
- google-cloud-logging

expect：

Supplement the above plug-ins. Temporarily skip the following two plug-ins:
- splunk-hec-logging
- google-cloud-logging

> They have a specific format and will not be adjusted for the time being.

### PR DESCRIPTION
**Pull request by smileby**
### Description

Fixes #10803

The request body and response body related attributes are added to the log plug-in. The list is as follows：
- elasticsearch-logger
- skywalking-logger
- syslog
- sls-logger
- tcp-logger
- udp-logger

upplement the description of existing attributes missing in the Chinese document. The list is as follows：
- loggly
- tencent-cloud-cls

### Checklist

- [X] I have explained the need for this PR and the problem it solves
- [X] I have explained the changes or the new features added to this PR
- [X] I have added tests corresponding to this change
- [X] I have updated the documentation to reflect this change
- [X] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by smileby** [comment]
@shreemaan-abhishek  Please help to check, thanks

**Comment by smileby** [comment]
@shreemaan-abhishek I don’t think the ci error is caused by this PR, please help check. Thanks

**Review by shreemaan-abhishek — CHANGES_REQUESTED** [review]
please provide test cases for other plugnis as well.

**Comment by smileby** [comment]
> please provide test cases for other plugnis as well.

Can the test cases be completed by adding logs in the plug-in? I can't seem to use assertions without increasing the log

**Comment by monkeyDluffy6017** [comment]
@smileby please resolve the conflicts

**Comment by smileby** [comment]
> @smileby please resolve the conflicts

Thanks for the reminder, I have solved it

**Comment by smileby** [comment]
> @smileby I didn't get you.

@shreemaan-abhishek  I added the info log in the plug-in to facilitate me to write test cases. The code has been submitted, please help to check, thank you

**Review by monkeyDluffy6017 — APPROVED** [review]

**Pull request merged**
