### PR TITLE
docs: update certificate names in decoupled mode and add configurations for different deployment modes to `config-default.yaml`

### LINKED ISSUE #9883: docs: all fields for certs in decoupled deployment modes use `/path/to/ca-cert`
### Current State

All fields for certs in decoupled deployment modes use `/path/to/ca-cert` as placeholders.

https://apisix.apache.org/docs/apisix/next/deployment-modes/#decoupled

For example:
image

This is inaccurate. Other than CA certificate, there are fields for server/client certificate and key.

### Desired State

Update the fields for certificates that are currently all `/path/to/ca-cert` to be more accurate.

### PR DESCRIPTION
**Pull request by kayx23**
### Description

* Update certificate names in decoupled mode
* Add configuration blocks of `role_data_plane` and `role_control_plane` in `config-default.yaml` to better document for different modes of APISIX deployment.

Fixes #9883 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by moonming** [comment]
Do we need to update https://github.com/apache/apisix/blob/master/conf/config-default.yaml too? I do not find these configures in this file.

**Comment by kayx23** [comment]
It looks to me that `config-default.yaml` includes only the configurations of **traditional mode** by default.

It doesn't include the configurations of **decoupled mode**, so you won't find these configurations in there.

It probably doesn't make sense to include both (even with one commented out) in that file because these deployment modes and configurations are conceptually mutually exclusive.

**Comment by moonming** [comment]
> It doesn't include the configurations of **decoupled mode**, so you won't find these configurations in there.

if so how do developers know decoupled mode configurations?

**Comment by kayx23** [comment]
Added configurations to `config-default.yaml`

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Pull request merged**
