### PR TITLE
docs: Fix the title naming issue

### LINKED ISSUE #7854: docs: Add How-to-guides section to APISIX Website API Gateway
### Current State

Currently, we have categorization based on plugins but there is no separation by usability cases.

Actually, plugins cover many things but It is hard to navigate through an exact fit plugin for some use cases without opening the individual plugin tutorial.

For newbies will be quite challenging to understand the core use cases of API Gateway.

### Desired State

We should have a How-to-guides section with learning content per each API Gateway use case that includes the following subpages:

Expose APIs
Protect APIs
Secure API
Monitor APIs
Improve performance. 
Health Check.
Add multiple versions. 
Cache API responses. 
Mock API responses.
Canary release. 
.... more

We have already enough blog posts that cover many API Gateway use cases we can rewrite them for each how-to guide page.

Here is the link to issue #6461

https://github.com/apache/apisix/issues/6461

You can see examples for Azure API Management or Kong API Gateway how the content is structured:

image

image

### PR DESCRIPTION
**Pull request by Boburmirzo**
### Description

Fixed the content title issue

Fixes #7854 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by Boburmirzo** [comment]
@hf400159 Could you help me to get merged this PR?

I found the issue with naming.

**Review by hf400159 — APPROVED** [review]

**Review by SylviaBABY — APPROVED** [review]

**Comment by Boburmirzo** [comment]
@hf400159 Just a moment! I think we need to convert How-to guides to Tutorials since most of our contents tech people:

Here the diff, I observed:

https://diataxis.fr/tutorials-how-to/

**Comment by Boburmirzo** [comment]
I will create another PR for the conversion to Tutorials.

**Comment by Boburmirzo** [comment]
> I will create another PR for the conversion to Tutorials.

We can merge this one

**Review by bzp2010 — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Comment by Boburmirzo** [comment]
Now I created new PR with both changes:

https://github.com/apache/apisix/pull/7938

Sorry for the inconvenience @LiteSun @hf400159 @SylviaBABY and @juzhiyuan

**Pull request closed without merging**
