### PR TITLE
add AK/SK auth plugin 

### LINKED ISSUE #1653: add AK/SK auth plugin

### PR DESCRIPTION
**Pull request by ChelinTsien**
### What this PR does / why we need it:

add ak/sk  auth plugin 
fix #1653. 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by ChelinTsien** [comment]
Document to be added later

**Comment by membphis** [comment]
> Document to be added later

yes, that is important

**Comment by membphis** [comment]
@ChelinTsien do you have time to update this PR, it still missing doc and test case now.

**Comment by ChelinTsien** [comment]
OK, I thought this pr was not adopted, I will find a time to add documentation and test cases

**Pull request closed without merging**
