### PR TITLE
feat: confirm only part of the etcd kvs

### PR DESCRIPTION
**Pull request by wfnuser**
### What this PR does / why we need it:

we only need to confirm part of result, returned list may change in the future.
#2800 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by membphis — CHANGES_REQUESTED** [review]
you can make a try with this way, it is simpler way.

```sh
make init
cmd_res=`etcdctl --endpoints=127.0.0.1:2379 --user=root:apache-api6 get /apisix --prefix`
etcdctl --endpoints=127.0.0.1:2379 --user=root:apache-api6 auth disable
etcdctl --endpoints=127.0.0.1:2379 role delete root
etcdctl --endpoints=127.0.0.1:2379 user delete root

count=`echo $cmd_res | grep -c "/apisix/global_rules" || true`
if [ $count -ne 1 ]; then
    echo "failed: failed to match '/apisix/global_rules'"
    exit 1
fi

**Comment by wfnuser** [comment]
> you can make a try with this way, it is simpler way.
> 
> ```shell
> make init
> cmd_res=`etcdctl --endpoints=127.0.0.1:2379 --user=root:apache-api6 get /apisix --prefix`
> etcdctl --endpoints=127.0.0.1:2379 --user=root:apache-api6 auth disable
> etcdctl --endpoints=127.0.0.1:2379 role delete root
> etcdctl --endpoints=127.0.0.1:2379 user delete root
> 
> count=`echo $cmd_res | grep -c "/apisix/global_rules" || true`
> if [ $count -ne 1 ]; then
>     echo "failed: failed to match '/apisix/global_rules'"
>     exit 1
> fi
> ```

Thx. This is really the simpler way. 
And I had some misunderstanding before. Actually we should check that there is some part of the ETCD keys must exists? If the particular key-value not exists in ETCD we should fail it.

**Comment by membphis** [comment]
Yes, you are right.

**Comment by wfnuser** [comment]
> Yes, you are right.

The pr is ready now.😄

**Review by membphis — APPROVED** [review]

**Comment by wfnuser** [comment]
Can we merge this pull request now? It seems that we need another approving review. @moonming

**Comment by membphis** [comment]
> Can we merge this pull request now? It seems that we need another approving review. @moonming

only 1 approval is not enough. we should wait for more time.

**Review by moonming — APPROVED** [review]

**Pull request merged**
