### PR TITLE
change: remove deprecated upstream.enable_websocket

### PR DESCRIPTION
**Pull request by spacewander**
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by Firstsawyou** [comment]
LGTM.

**Review by imjoey — APPROVED** [review]
/lgtm

**Comment by tokers** [comment]
@spacewander The document also should be updated.

**Comment by spacewander** [comment]
The doc has been updated before.

**Review by tokers — APPROVED** [review]

**Pull request merged**
