### PR TITLE
feat: Build docker image in source code

### PR DESCRIPTION
**Pull request by gy09535**
### What this PR does / why we need it:
fix: https://github.com/apache/apisix-docker/issues/86
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Waiting for the discuss result.

[1] https://github.com/apache/apisix/issues/2249

**Comment by gy09535** [comment]
I copy Dockerfile  from https://github.com/apache/apisix-docker/blob/master/alpine/Dockerfile , And replace build code from local other then form github.

**Comment by gy09535** [comment]
any update?

**Comment by gxthrj** [comment]
I think it is related to #2783

**Comment by moonming** [comment]
where is the source code？ I not find in dockerfile

**Comment by gy09535** [comment]
> where is the source code？ I not find in dockerfile

https://github.com/apache/apisix/pull/2250/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R19

This Dockerfile is put in apisix root path, when user clone this project, And then can build docker image use command 
```
docker build -t apisix:tags 
```.

**Pull request closed without merging**
