### PR TITLE
docs: fix the indent of README.md

### PR DESCRIPTION
**Pull request by yujqiao**
This PR should be a no-brainer.

### What this PR does / why we need it:

The original README is misaligned. This PR aligns the indent in Get Started properly.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by leslie-tsang** [comment]
Hello there, Would you mind checking if other documents have the same issue. like [`CN Readme`](https://github.com/apache/apisix/blob/2b239077432a8af1812c5f95fc5f01b748abaabf/docs/zh/latest/README.md?plain=1#L152-L156)

**Comment by rapiz1** [comment]
Corresponding changes were made.

**Comment by leslie-tsang** [comment]
> I suppose the CI failures were irrelevant to this PR and may reflect some problem in the master branch?

Working on it.

**Comment by spacewander** [comment]
Let's merge master to make CI pass.

**Pull request merged**
