### PR TITLE
bug(CLI): CI failed, failed to load `apisix.cli.ngx_tpl`

### LINKED ISSUE #2587: bug: CI failed, failed to load `apisix.cli.ngx_tpl`
https://github.com/apache/apisix/runs/1336136679#step:10:29

@tokers do you have time to look at this issue?

### PR DESCRIPTION
**Pull request by membphis**
### What this PR does / why we need it:

fix #2587

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by membphis** [comment]
@tokers please take a look at this PR

**Comment by tokers** [comment]
Sorry, I'm outside now, I will fix it in the afternoon.

**Comment by membphis** [comment]
> Sorry, I'm outside now, I will fix it in the afternoon.

I have fixed it. just make sure I fixed it in the right way.

**Review by spacewander — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Comment by tokers** [comment]
> > Sorry, I'm outside now, I will fix it in the afternoon.
> 
> I have fixed it. just make sure I fixed it in the right way.

LGTM, sorry for my careless.

**Pull request merged**
