### PR TITLE
docs: added installation mode for LTS version

### PR DESCRIPTION
**Pull request by Chever-John**
### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by SkyeYoung** [comment]
Why not just give the tip to install the LTS version in step 1? Now I had to jump back to step 1 and look at it again.

**Comment by SkyeYoung** [comment]
> Why not just give the tip to install the LTS version in step 1? 

Just like [here](https://apisix.apache.org/zh/docs/apisix/getting-started#:~:text=Apache%20APISIX%20%E5%B7%B2%E6%94%AF%E6%8C%81%20ARM64%20%E6%9E%B6%E6%9E%84%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E6%AD%A3%E5%9C%A8%E4%BD%BF%E7%94%A8%20ARM64%EF%BC%8C%E8%AF%B7%E5%9C%A8%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E6%89%A7%E8%A1%8C%20docker%2Dcompose%20%2Dp%20docker%2Dapisix%20%2Df%20docker%2Dcompose%2Darm64.yml%20up%20%2Dd%E3%80%82)

**Comment by tzssangglass** [comment]
pls add en docs too

**Comment by Chever-John** [comment]
> > Why not just give the tip to install the LTS version in step 1?
> 
> Just like [here](https://apisix.apache.org/zh/docs/apisix/getting-started#:~:text=Apache%20APISIX%20%E5%B7%B2%E6%94%AF%E6%8C%81%20ARM64%20%E6%9E%B6%E6%9E%84%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E6%AD%A3%E5%9C%A8%E4%BD%BF%E7%94%A8%20ARM64%EF%BC%8C%E8%AF%B7%E5%9C%A8%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E6%89%A7%E8%A1%8C%20docker%2Dcompose%20%2Dp%20docker%2Dapisix%20%2Df%20docker%2Dcompose%2Darm64.yml%20up%20%2Dd%E3%80%82)

**Comment by Chever-John** [comment]
> Why not just give the tip to install the LTS version in step 1? Now I had to jump back to step 1 and look at it again.

Since this article is mainly about installing the current version, the LTS version is only an additional option.

**Comment by SkyeYoung** [comment]
> Since this article is mainly about installing the current version, the LTS version is only an additional option.

Affirmative, so you should make it as a TIP, right?

**Comment by Chever-John** [comment]
> 

Adding a hint, I think, would compromise the integrity of the description.
If there is a way to install the LTS version, I think he should look at the installation directory first.

**Comment by SkyeYoung** [comment]
>If there is a way to install the LTS version, I think he should look at the installation directory first.

So, have you visited this link? Is it wrong?

> Just like [here](https://apisix.apache.org/zh/docs/apisix/getting-started#:~:text=Apache%20APISIX%20%E5%B7%B2%E6%94%AF%E6%8C%81%20ARM64%20%E6%9E%B6%E6%9E%84%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E6%AD%A3%E5%9C%A8%E4%BD%BF%E7%94%A8%20ARM64%EF%BC%8C%E8%AF%B7%E5%9C%A8%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E6%89%A7%E8%A1%8C%20docker%2Dcompose%20%2Dp%20docker%2Dapisix%20%2Df%20docker%2Dcompose%2Darm64.yml%20up%20%2Dd%E3%80%82)

**Comment by Chever-John** [comment]
The [link](https://apisix.apache.org/zh/docs/apisix/getting-started#:~:text=Apache%20APISIX%20%E5%B7%B2%E6%94%AF%E6%8C%81%20ARM64%20%E6%9E%B6%E6%9E%84%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E6%AD%A3%E5%9C%A8%E4%BD%BF%E7%94%A8%20ARM64%EF%BC%8C%E8%AF%B7%E5%9C%A8%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E6%89%A7%E8%A1%8C%20docker%2Dcompose%20%2Dp%20docker%2Dapisix%20%2Df%20docker%2Dcompose%2Darm64.yml%20up%20%2Dd%E3%80%82) you put forward is misleading to me. If you mean to add tips on LTS installation at [link](https://apisix.apache.org/docs/apisix/how-to-build/#:~:text=You%20can%20install%20Apache%20APISIX%20via%20RPM%20Repository%2C%20Docker%2C%20Helm%20Chart%2C%20and%20source%20release%20package.%20Please%20choose%20one%20from%20the%20following%20options.), I think it is feasible

**Review by starsz — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]

**Review by zaunist — APPROVED** [review]

**Pull request merged**
