### PR TITLE
fix: upstream dns resolver failed response 503

### PR DESCRIPTION
**Pull request by syzh**
fixed issue #3342.

### CODE REVIEW

**Comment by spacewander** [comment]
Need to update the tests.

**Review by spacewander — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Comment by syzh** [comment]
> Need to update the tests.

I need some time to add more tests case

**Comment by spacewander** [comment]
@syzh 
You just need to update the expected status code in the tests.

**Comment by Firstsawyou** [comment]
Hi, @syzh 

You need to update the test case to solve the problem of ci failure.

For example: `TEST 8` of the upstream2.t test case, you need to change `502` to `503`.

```
#   Failed test 'TEST 8: hit empty nodes upstream - status code ok'
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 935.
#          got: '503'
#     expected: '502'
# Looks like you failed 1 test of 30.
t/admin/upstream2.t ....................... 
Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by membphis** [comment]
ping @syzh

**Pull request merged**
