### PR TITLE
docs: updated screenshots from v2.x dashboard 

### PR DESCRIPTION
**Pull request by iamayushdas**
### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by iamayushdas** [comment]
i have only added screenshots from jwt-auth.md and key-auth.md . just wanted to know if those screenshots are correct or not
@juzhiyuan

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
LGTM, and please clean your commits in the future PR :)

**Comment by iamayushdas** [comment]
> LGTM, and please clean your commits in the future PR :)

okay i will :)

**Comment by iamayushdas** [comment]
@juzhiyuan i am not able to take  other screenshots because some of the components are not loading at all. 
link i am using is : http://139.217.190.60/
* [ ] jwt-auth.md 
* [ ] key-auth.md

other plugin screenshots are not uploaded due to this error
Page not loading

**Comment by juzhiyuan** [comment]
image


Hi, could you please refresh the page? for the server is in China 🤔

**Comment by iamayushdas** [comment]
> image
> 
> Hi, could you please refresh the page? for the server is in China

i have refreshed it many times

**Comment by iamayushdas** [comment]
> > Hi, could you please refresh the page? for the server is in China
> 
> i have refreshed it many times

now it worked via vpn

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
