### PR TITLE
feat: add body match in active health check

### LINKED ISSUE #10517: feat: As a user, I want to specify an "expected string" in http health checks
### Description

As a user, I want to specify an "expected string" parameter in the definition of an http health check, so that APISIX can tell when a webserver is not interpreting the programming language correctly and instead serves the files in plain-text.

For example, if the expected string is `pass` and I generate it with something like `echo 'p', 'a', 's', 's';`, the health check will disable the machine when the php code is not interpreted. Yes, it might take down all the nodes, but that's preferable to the other scenario, where the underlying code is displayed on the webpage.

### PR DESCRIPTION
**Pull request by theweakgod**
### Description
Add body match in active health check.

Fixes #10517  (https://github.com/apache/apisix/issues/10517)

Add the body_match_str parameter in the lua-resty-healthcheck module to check if the response body matches the expected string.

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
The pr is not ready, right?

**Comment by theweakgod** [comment]
> The pr is not ready, right?

https://github.com/api7/lua-resty-healthcheck/pull/43
This should be combined with this pr

**Comment by monkeyDluffy6017** [comment]
OK, thanks for your contribution, this pr should merged after https://github.com/api7/lua-resty-healthcheck/pull/43, and we need to upgrade the lua-resty-healthcheck version in APISIX, the next version of lua-resty-healthcheck should be 3.2.1

**Comment by monkeyDluffy6017** [comment]
I've taken a closer look at the requirement and I've realised that it's not very clear and there's probably no way to make it a very generic feature, e.g. whether the health check request sent needs to carry a specific body of the request, whether the health check result returned should be checked for a particular field or for the whole result.
These 2 issues describe 2 different requirements: https://github.com/apache/apisix/issues/10517 and https://github.com/apache/apisix/issues/9920

**Comment by theweakgod** [comment]
> I've taken a closer look at the requirement and I've realised that it's not very clear and there's probably no way to make it a very generic feature, e.g. whether the health check request sent needs to carry a specific body of the request, whether the health check result returned should be checked for a particular field or for the whole result. These 2 issues describe 2 different requirements: #10517 and #9920



> I've taken a closer look at the requirement and I've realised that it's not very clear and there's probably no way to make it a very generic feature, e.g. whether the health check request sent needs to carry a specific body of the request, whether the health check result returned should be checked for a particular field or for the whole result. These 2 issues describe 2 different requirements: #10517 and #9920

I think it is better for the health check to do a simple whole-body verification, without considering the content-type. Some users may really need a simple body verification to determine whether they are healthy. If you target a certain field, different content-types will make the parsing more complicated. I think the easiest and best way at present is to verify the entire body.

**Comment by monkeyDluffy6017** [comment]
let's hold this pr to see if others agree with this design, there are a number of designs that use a heartbeat mechanism, such as sending `aabb`, then checking to see if what is received is `bbaa`

**Comment by theweakgod** [comment]
> let's hold this pr to see if others agree with this design, there are a number of designs that use a heartbeat mechanism, such as sending `aabb`, then checking to see if what is received is `bbaa`

Alright, I got it

**Pull request closed without merging**
