### PR TITLE
docs: update "Loggers" Plugins 1/n

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

### Description

Updates the documentation of the "Observability/Loggers" Plugins (1/n).

Child PR of #6734

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
// @hf400159 @kwanhur @avinal @yzeng25 @juzhiyuan Please review when you are available.

**Review by juzhiyuan — APPROVED** [review]

**Comment by kwanhur** [comment]
LGTM

**Comment by juzhiyuan** [comment]
cc @hf400159 Please help to review ~ thanks

**Review by hf400159 — APPROVED** [review]
LGTM

**Review by SylviaBABY — APPROVED** [review]

**Review by avinal — APPROVED** [review]
Looks great!

**Pull request merged**
