### PR TITLE
feat: add a tool that can help users quickly try your project

### PR DESCRIPTION
**Pull request by JiaoMaMJ**
### add a tool that can help users quickly try your project:

 Hello, we are TeamCode. We have created a Tin application for your project, which help your users to quickly run and try your project without having to install and configure the environment. You don’t need to pay for this service. Hope it can help you better promote the project. Thx.
you can try it: https://www.teamcode.com/tin/clone?applicationId=254296249567039488
Read the guide: https://www.teamcode.com/docs/en-US/tin/clone-tin

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by tokers** [comment]
@JiaoMaMJ Thanks for your contribution! It's great!

Let's resolve the conflicts so that we can merge it to the master.

**Review by spacewander — COMMENTED** [review]
I think we should discuss it in the mail list first?

**Review by spacewander — APPROVED** [review]

**Review by spacewander — CHANGES_REQUESTED** [review]
Sorry for the wrong operation. I have not approved this PR yet. We should discuss it in the mail list first.

**Review by moonming — CHANGES_REQUESTED** [review]
IMO, we need to discuss in ML first, TeamCode is a commercial product and requires user login to use

**Comment by JiaoMaMJ** [comment]
> IMO, we need to discuss in ML first, TeamCode is a commercial product and requires user login to use

Hi, I sent a mail to the address: dev-subscribe@apisix.apache.org . Hope the letter will resolve your concerns. Looking forward to your reply.

**Comment by juzhiyuan** [comment]
> > IMO, we need to discuss in ML first, TeamCode is a commercial product and requires user login to use
> 
> Hi, I sent a mail to the address: [dev-subscribe@apisix.apache.org](mailto:dev-subscribe@apisix.apache.org) . Hope the letter will resolve your concerns. Looking forward to your reply.

Hi, please follow https://apisix.apache.org/docs/general/subscribe-guide to subscribe the mailing list 😄

**Review by juzhiyuan — CHANGES_REQUESTED** [review]
Hi @JiaoMaMJ, I just noticed that in TeamCode's Docs[1], there has a screenshot as follows:

image

Does it seem that this screenshot is made manually? 

[1] https://www.teamcode.com/docs/tin/share-github

**Comment by JiaoMaMJ** [comment]
> 

Yes, It is a manual screenshot, just to demonstrate the entrance effect. You can customize the actual display effect. If your project uses Tin, we will also promote your product on our website, in the  Scenario page of document.

**Comment by juzhiyuan** [comment]
> > 
> 
> Yes, It is a manual screenshot, just to demonstrate the entrance effect. You can customize the actual display effect. If your project uses Tin, we will also promote your product on our website, in the Scenario page of document.

Get it, and please follow https://apisix.apache.org/docs/general/subscribe-guide to send a DISCUSS mail, thanks 😄

**Comment by JiaoMaMJ** [comment]
> > > 
> > 
> > 
> > Yes, It is a manual screenshot, just to demonstrate the entrance effect. You can customize the actual display effect. If your project uses Tin, we will also promote your product on our website, in the Scenario page of document.
> 
> Get it, and please follow https://apisix.apache.org/docs/general/subscribe-guide to send a DISCUSS mail, thanks 😄

I have succeeded in subscribing Apache APISIX mailing-list，and send a DISCUSS mail to the cummunity. Looking forward to your reply:)

**Comment by JiaoMaMJ** [comment]
> > > 
> > 
> > 
> > Yes, It is a manual screenshot, just to demonstrate the entrance effect. You can customize the actual display effect. If your project uses Tin, we will also promote your product on our website, in the Scenario page of document.
> 
> Get it, and please follow https://apisix.apache.org/docs/general/subscribe-guide to send a DISCUSS mail, thanks 😄

I have succeeded in subscribing Apache APISIX mailing-list，and send a DISCUSS mail to the cummunity. Looking forward to your reply:)

**Pull request closed without merging**
