### PR TITLE
docs: add chinese version of dubbo-proxy.md

### PR DESCRIPTION
**Pull request by supermario1990**
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Review by spacewander — CHANGES_REQUESTED** [review]
Need to update https://github.com/apache/apisix/blob/master/docs/zh/latest/config.json too

**Comment by juzhiyuan** [comment]
yes, @supermario1990 please update that file just like `/en/latest/config.json` does :)

**Comment by supermario1990** [comment]
> yes, @supermario1990 please update that file just like `/en/latest/config.json` does :)

sorry， i compared  `/en/latest/config.json` with `/zh/latest/config.json` and i'm still confused, Where should I update about `config.json`?

**Review by spacewander — APPROVED** [review]
My bad. The config.json is already updated.

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
