### PR TITLE
chore: tweak the uri to view plug-in types

### PR DESCRIPTION
**Pull request by tzssangglass**
/apisix/admin/plugins/?all=true to /apisix/admin/plugins?all=true

### What this PR does / why we need it:

fix https://github.com/apache/apisix/pull/2886#discussion_r549553878

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by tzssangglass** [comment]
ping @juzhiyuan @spacewander

**Review by spacewander — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by qwxingzhe** [comment]
image
@spacewander @tzssangglass I can't run it. Do you have any preconditions

**Comment by tzssangglass** [comment]
> image
> @spacewander @tzssangglass I can't run it. Do you have any preconditions

Have you updated to the latest code for the master branch?This looks like running code that does not contain this commit.

**Comment by qwxingzhe** [comment]
> > image
> > @spacewander @tzssangglass I can't run it. Do you have any preconditions
> 
> Have you updated to the latest code for the master branch?This looks like running code that does not contain this commit.

Is it necessary to indicate the supported version of each interface in the document?

**Comment by spacewander** [comment]
@qwxingzhe 
We can do it after 2.2 is released.

**Pull request merged**
