### PR TITLE
fix: the limit-conn plugin cannot effectively intercept requests in special scenarios

### PR DESCRIPTION
**Pull request by zuiyangqingzhou**
### What this PR does / why we need it:

fix [4556](https://github.com/apache/apisix/issues/4556)

ps: I will add test cases in the next two days

### CODE REVIEW

**Comment by tokers** [comment]
@zuiyangqingzhou The PR title is subtle, it cannot reflect what did this PR do. Please change it.

**Comment by zuiyangqingzhou** [comment]
> @zuiyangqingzhou The PR title is subtle, it cannot reflect what did this PR do. Please change it.

sorry, i will fix it

**Comment by spacewander** [comment]
@zuiyangqingzhou 
Would you add some test case?

**Comment by zuiyangqingzhou** [comment]
> @zuiyangqingzhou
> Would you add some test case?

sorry, this week is busy, I will try my best to add test case, or if you are willing to help me, I will thank you very much

**Comment by spacewander** [comment]
> 
> 
> > @zuiyangqingzhou
> > Would you add some test case?
> 
> sorry, this week is busy, I will try my best to add test case, or if you are willing to help me, I will thank you very much

I will take care of it soon.

**Comment by zuiyangqingzhou** [comment]
> > > @zuiyangqingzhou
> > > Would you add some test case?
> > 
> > 
> > sorry, this week is busy, I will try my best to add test case, or if you are willing to help me, I will thank you very much
> 
> I will take care of it soon.

awesome, 👍🏻

**Review by spacewander — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Pull request merged**
