### PR TITLE
test: split prometheus test case

### LINKED ISSUE #3561: test unstable: t/plugin/prometheus.t
### Issue description

Test failed in CI.

```
Error: led test 'TEST 45: set route with key-auth enabled for consumer metrics - pattern "[error]" should not match any line in error.log but matches line "2021/02/08 13:52:26 [error] 21196#21196: *3795 [lua] config_yaml.lua:66: failed to fetch /home/runner/work/apisix/apisix/t/servroot/conf/apisix.yaml attributes: cannot obtain information from file '/home/runner/work/apisix/apisix/t/servroot/conf/apisix.yaml': No such file or directory, context: ngx.timer" (req 0)
# 2021/02/08 13:52:26 [error] 21195#21195: *3798 [lua] config_yaml.lua:66: failed to fetch /home/runner/work/apisix/apisix/t/servroot/conf/apisix.yaml attributes: cannot obtain information from file '/home/runner/work/apisix/apisix/t/servroot/conf/apisix.yaml': No such file or directory, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3781 [lua] plugin.lua:547: checker(): check plugin schema, name: prometheus, configurations: {}, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3781 [lua] service.lua:88: filter(): filter service: {"value":{"update_time":1612792326,"plugins":{"prometheus":{}},"upstream":{"parent":{"value":"table: 0x7f0dbfc7bc90","clean_handlers":{},"modifiedIndex":8392,"has_domain":false,"key":"\/apisix\/services\/1","createdIndex":8392},"type":"roundrobin","hash_on":"vars","scheme":"http","nodes":[{"host":"127.0.0.1","port":1980,"weight":1}],"pass_host":"pass"},"id":"1","create_time":1612792326},"clean_handlers":"table: 0x7f0dbf867e98","modifiedIndex":8392,"has_domain":false,"key":"\/apisix\/services\/1","createdIndex":8392}, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3779 [lua] plugin.lua:547: checker(): check plugin schema, name: prometheus, configurations: {}, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3783 [lua] v3.lua:34: _request_uri(): v3 request uri: http://127.0.0.1:2379/v3/kv/put, timeout: 30, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3775 [lua] v3.lua:563: request_chunk(): http request method: POST path: /v3/watch body: {"create_request":{"range_end":"L2FwaXNpeC9yb3V0ZXQ=","start_revision":8459,"key":"L2FwaXNpeC9yb3V0ZXM="}} query: nil, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3789 [lua] v3.lua:563: request_chunk(): http request method: POST path: /v3/watch body: {"create_request":{"range_end":"L2FwaXNpeC9jb25zdW1lcnQ=","start_revision":8459,"key":"L2FwaXNpeC9jb25zdW1lcnM="}} query: nil, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3787 [lua] v3.lua:563: request_chunk(): http request method: POST path: /v3/watch body: {"create_request":{"range_end":"L2FwaXNpeC9wbHVnaW5fbWV0YWRhdGI=","start_revision":8459,"key":"L2FwaXNpeC9wbHVnaW5fbWV0YWRhdGE="}} query: nil, context: ngx.timer
# 2021/02/08 13:52:26 [info] 21253#21253: *3777 [lua] v3.lua:563: request_chunk(): http request method: POST path: /v3/watch body: {"create_request":{"range_end":"L2FwaXNpeC9zc20=","start_revision":8459,"key":"L2FwaXNpeC9zc2w="}} query: nil, context: ngx.timer
# '
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 1280.
```

### Environment

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): ubunt-18.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.15
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### PR DESCRIPTION
**Pull request by spacewander**
Fix #3561

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by spacewander** [comment]
This change avoid a race in the test framework.
Also make the very long test bearable.

**Review by lilien1010 — APPROVED** [review]
should we make some limmitaions of one single test file？

**Comment by Yiyiyimu** [comment]
Is the problem caused by defining `apisix_yaml` in test 44? If yes, do we need to worry about other tests which have the same customized yaml?

**Comment by spacewander** [comment]
> 
> 
> Is the problem caused by defining `apisix_yaml` in test 44? If yes, do we need to worry about other tests which have the same customized yaml?

To trigger the error we need `TEST_NGINX_USE_HUP` set. So other tests are not affected.

**Comment by spacewander** [comment]
> 
> 
> should we make some limmitaions（lines or test cases） for one single test file？

What about 800 lines or 30 tests?

**Comment by Yiyiyimu** [comment]
> To trigger the error we need `TEST_NGINX_USE_HUP` set. So other tests are not affected.

Thanks a lot for the explanation!

**Review by Yiyiyimu — APPROVED** [review]

**Pull request merged**
