### PR TITLE
refactor: separate admin and proxy port in default config

### PR DESCRIPTION
**Pull request by ShiningRush**
Recently, we have a serious security vulnerability caused by `adminapi`.
I synchronize  scenarios here:
- Some external business team forget to modify admin port and key after debugging(the ip whitelist is removed), so that anyone can access the `adminapi`
- Some people using the default admin key to scan `adminapi` and found the command execution vulnerability, they reported it to the our company's security platform

I think there are two points we can optimize:
- the default configuration is to separate proxy and admin port
- `adminapi` command execution vulnerability.I will push a PR to apisix after I produce and fix the vulnerability

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Comment by spacewander** [comment]
Note: merge it after 2.1 is released and works well.

**Review by juzhiyuan — COMMENTED** [review]
🤔 Just to make sure, I only see there have docs changed, does it will resolve the vulnerable?

**Comment by spacewander** [comment]
@juzhiyuan 
` conf/config-default.yaml` is changed.

**Comment by juzhiyuan** [comment]
> @juzhiyuan 
> ` conf/config-default.yaml` is changed.

Oh yes!

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
