### PR TITLE
feat(CI): create markdown-link-checker.yml

### PR DESCRIPTION
**Pull request by juzhiyuan**
### What this PR does / why we need it:

We could use this CI to check if links in markdown files are alive.

related issue #2681 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Now we have all broken links, let's just updated the CI to check only modified files. Broken links would be found here https://github.com/apache/apisix/pull/2684/checks?check_run_id=1377811587

**Review by LiteSun — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
Hi @juzhiyuan 

The configuration I'm using is 
```
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/checklink_config.json'
```

and checklink_config.json

```
{
  "ignorePatterns": [
    {
      "pattern": ["^/img/"]
    },
    {
      "pattern": ["^http://localhost"]
    },
    {
      "pattern": ["^https://github.com"]
    }
  ]
}
```
So it's like we need to manually filter out some example links, and some links that have strict anti-spider strategies.

Maybe that would be of help 😃

**Comment by juzhiyuan** [comment]
👏🏻Ya, and if we could uniform example links when improving docs.

**Comment by Yiyiyimu** [comment]
> 👏🏻Ya, and we could uniform example links when improving docs.

Yeah that's a good point!

**Pull request merged**
