### PR TITLE
[WIP] feat snowflake plugin

### PR DESCRIPTION
**Pull request by dickens7**
#4209 

This PR is a draft version, used to discuss implementation

### CODE REVIEW

**Comment by moonming** [comment]
I am not sure that do we should add a plugin for request id?

**Comment by Yiyiyimu** [comment]
> I am not sure that do we should add a plugin for request id?

Agreed. Since it's an alternative algorithm for request-id, it might be better to add an enum argument to request-id, instead of using it as another plugin

**Comment by dickens7** [comment]
> > I am not sure that do we should add a plugin for request id?
> 
> Agreed. Since it's an alternative algorithm for request-id, it might be better to add an enum argument to request-id, instead of using it as another plugin

It is planned like this. Now we are solving the problem that the snowflake algorithm can only have 1024 workers

**Comment by Yiyiyimu** [comment]
> It is planned like this. Now we are solving the problem that the snowflake algorithm can only have 1024 workers

Do you mind sharing the reason for "planned like this"

**Comment by dickens7** [comment]
Refactor

**Pull request closed without merging**
