### PR TITLE
chore(chaitin-waf): Update dep lua-resty-t1k to 1.1.5

### PR DESCRIPTION
**Pull request by xbingW**
fix: incorrect handling of multiple header values in HTTP/2

lua-resty-t1k released v1.1.5, which fixed the problem of multiple values ​​for the same key in the HTTP/2 request header causing detection failure.

### Description

Fixes # (issue)

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by moonming — APPROVED** [review]

**Review by shreemaan-abhishek — DISMISSED** [review]

**Review by bzp2010 — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Comment by moonming** [comment]
@xbingW is this PR ready?

**Comment by xbingW** [comment]
> @xbingW is this PR ready?

yes

**Comment by moonming** [comment]
@bzp2010 @shreemaan-abhishek please review again

**Review by shreemaan-abhishek — APPROVED** [review]

**Comment by xbingW** [comment]
https://github.com/orgs/community/discussions/58535?sort=top#discussioncomment-6233887
Maybe I have encountered this problem. Do I need to close and reopen PR?

**Comment by moonming** [comment]
> https://github.com/orgs/community/discussions/58535?sort=top#discussioncomment-6233887 Maybe I have encountered this problem. Do I need to close and reopen PR?

ok, you can make a try

**Comment by xbingW** [comment]
@bzp2010 @shreemaan-abhishek please review again

**Review by bzp2010 — APPROVED** [review]

**Review by shreemaan-abhishek — APPROVED** [review]

**Pull request merged**
