### PR TITLE
docs: optimization curl command

### PR DESCRIPTION
**Pull request by xuanyanwow**
### What this PR does / why we need it:

In some special env. the test curl command may get the error result.
optimization the command in docs.
``` sh
# curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
{"error_msg":"failed to check token"}
curl: (6) Could not resolve host: edd1c9f034335f136f87ad84b625c8f1'
```
references： https://blog.csdn.net/u011035397/article/details/109452045

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by kwanhur** [comment]
`curl` examples appear everywhere in `docs`, should be optimized along with all the others.

**Review by spacewander — CHANGES_REQUESTED** [review]
This doesn't bring any difference whether we use the single quote for the header or not.

**Comment by spacewander** [comment]
Please don't trust a piece of very doubtful information copied from someone's blog. It is a waste of both your time and mine.

**Comment by spacewander** [comment]
I guess you forgot to paste a quote during copy & paste, so `edd1c9f034335f136f87ad84b625c8f1` is not quoted and is treated as the target.

Please learn the difference between single quotes and double quotes via `man bash`, instead of believing an idea from an unreliable platform.

**Comment by xuanyanwow** [comment]
I make sure what i have not forgot the quote, and i try to use -d or other param with single quote, only the -H working error.
And this question only show in my one computer, another is normal.
I will try to find more info and test about this question, and then take a discuss here.
Thank you all.

**Comment by xuanyanwow** [comment]
Because i test in windows with docker.

Now i can make sure the question by use ` fiddler ` to get the  request info.
It is because windows'cmd cannot parse single quote ,but it's have a little diffrent .

``` 
curl -H 'X: 123'
```
it can not parse ,throw the error `curl: (6) Could not resolve host:...`

```
curl -H 'X:123'
```
it will not throw the error ,but it's not a normal http's header.

**Pull request closed without merging**
