### PR TITLE
ci(arm64):  core module support arm64 circleci

### PR DESCRIPTION
**Pull request by soulbird**
### Description

support arm64 circleci for core module:

```bash
t/admin t/cli t/config-center-yaml t/control t/core t/debug t/error_page t/misc
t/node t/router t/script t/stream-node t/utils t/xds-library t/xrpc
```

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by moonming — COMMENTED** [review]
Is circleci running？

**Comment by soulbird** [comment]
> 
I have run circleci on api7/apisix, and it passed. You can see: https://app.circleci.com/pipelines/github/api7/apisix/3/workflows/b4e0b971-d286-43a1-8338-ddcfa55f486d.

When this PR merged in apache/apisix, I will sync it to api7/apisix. At last, circleci will run in api7/apisix

**Comment by soulbird** [comment]
> Is circleci running？

I have run circleci on api7/apisix, and it passed. You can see: https://app.circleci.com/pipelines/github/api7/apisix/3/workflows/b4e0b971-d286-43a1-8338-ddcfa55f486d.

When this PR merged in apache/apisix, I will sync it to api7/apisix. At last, circleci will run in api7/apisix

**Comment by moonming** [comment]
> 

What? Apache APISIX will not merge this PR, because it's nothing with APISIX.

**Pull request closed without merging**
