### PR TITLE
fix: bump lua-resty-rocketmq to 0.3.0-0

### PR DESCRIPTION
**Pull request by yuz10**
### What this PR does / why we need it:

fix the lua-resty-rocketmq module crash after send more than 65535 messages.

see https://github.com/yuz10/lua-resty-rocketmq/commit/027d4382a836a10bda9200a8c644f45b8c111a38

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi @yuz10, please help to check the failed CI, would better also check the checklist 😄

**Comment by yuz10** [comment]
> Hi @yuz10, please help to check the failed CI, would better also check the checklist 😄

I Think the CI is unstable, can you retry it?

**Comment by juzhiyuan** [comment]
sure, just rerun.

**Review by tokers — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
@yuz10 many thx for your contribution

**Comment by yuz10** [comment]
@membphis   My pleasure. I am happy to work together with apisix community, it is a warm and great community, thanks a lot.

**Comment by juzhiyuan** [comment]
Glad to hear that 😄

**Pull request merged**
