### PR TITLE
docs: updated the architecture diagram

### PR DESCRIPTION
**Pull request by iamayushdas**
### What this PR does / why we need it:
Updated the architecture - admin API replaced with Manager API
[#307](https://github.com/apache/apisix-website/issues/307) from apisix-website

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by iamayushdas** [comment]
@juzhiyuan @Yiyiyimu @membphis strange error has occured
Help!

**Comment by juzhiyuan** [comment]
😳😳 Wht this image will get conflict?

**Comment by juzhiyuan** [comment]
@iamayushdas BTW, I think we couldn't update this repo, because this repo doesn't contain dashboard 😂 We only need to use the image from `apisix-dashboard` and attach it to `apisix-website`

**Comment by iamayushdas** [comment]
> @iamayushdas BTW, I think we couldn't update this repo, because this repo doesn't contain dashboard  We only need to use the image from `apisix-dashboard` and attach it to `apisix-website`

ah! ok

**Comment by iamayushdas** [comment]
> > @iamayushdas BTW, I think we couldn't update this repo, because this repo doesn't contain dashboard  We only need to use the image from `apisix-dashboard` and attach it to `apisix-website`
> 
> ah! ok , but i still didn't understand why this conflict will occur

**Comment by Yiyiyimu** [comment]
> @juzhiyuan @Yiyiyimu @membphis strange error has occured
> Help!

BTW, if you met with it again, you could try `git merge master -s ours`, although I couldn't understand the conflict either 🤣

**Comment by iamayushdas** [comment]
> > @iamayushdas BTW, I think we couldn't update this repo, because this repo doesn't contain dashboard  We only need to use the image from `apisix-dashboard` and attach it to `apisix-website`
> 
> ah! ok

but why this conflict will occur i didn't understand

**Comment by iamayushdas** [comment]
> @iamayushdas BTW, I think we couldn't update this repo, because this repo doesn't contain dashboard  We only need to use the image from `apisix-dashboard` and attach it to `apisix-website`

i remember last time when i changed the image compatibility for dark mode, i updated the same repo

**Comment by juzhiyuan** [comment]
🤔 Because APISIX doesn't have `dashboard`, so the image doesn't need it too 😂

**Comment by iamayushdas** [comment]
>  Because APISIX doesn't have `dashboard`, so the image doesn't need it too

[#307](https://github.com/apache/apisix-website/issues/307)
so this issue should be on hold right now

**Comment by iamayushdas** [comment]
>  Because APISIX doesn't have `dashboard`, so the image doesn't need it too

should i remove the dashboard part for now?

**Comment by juzhiyuan** [comment]
Maybe:

1. Cope the image link from the dashboard repo;
2. File a PR in the apisix-website repo;

**Comment by iamayushdas** [comment]
> Maybe:
> 
> 1. Cope the image link from the dashboard repo;
> 2. File a PR in the apisix-website repo;

 that image has solid background have to change that repo too

**Pull request closed without merging**
