### PR TITLE
docs: update web interface to latest

### PR DESCRIPTION
**Pull request by okaybase**
### What this PR does / why we need it:

Update web interface to latest for plugins:

- basic-auth
- key-auth
- limit-conn
- limit-count
- limit-req
- skywalking
- wolf-rbac
- zipkin

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by spacewander — COMMENTED** [review]
Could you help to solve this issue?
https://github.com/apache/apisix/issues/3711

**Comment by okaybase** [comment]
> Could you help to solve this issue?
> #3711

okay~
the change(has committed) in current pr is ok?

**Comment by spacewander** [comment]
> 
> 
> > Could you help to solve this issue?
> > #3711
> 
> okay~
> the change(has committed) in current pr is ok?

LGTM

**Review by tokers — APPROVED** [review]

**Comment by okaybase** [comment]
Hi @spacewander done~

**Review by spacewander — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
