### PR TITLE
docs: updated to new users-wall in powered-by.md

### PR DESCRIPTION
**Pull request by iamayushdas**
### What this PR does / why we need it:
 updated to new users-wall in powered-by.md

link: https://github.com/apache/apisix/blob/master/powered-by.md

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi, would you please clean your commits history 😊

**Comment by iamayushdas** [comment]
> Hi, would you please clean your commits history

would take care of it next time. please review it this time

**Comment by spacewander** [comment]
@iamayushdas 
Please fix it now. No "next time".

**Comment by iamayushdas** [comment]
@juzhiyuan i have cleaned it now. check please
:)

**Comment by juzhiyuan** [comment]
It seems that there have some historical changes 🤔

**Comment by iamayushdas** [comment]
> It seems that there have some historical changes

all good now?

**Comment by iamayushdas** [comment]
> > It seems that there have some historical changes
> 
> all good now?

@juzhiyuan @spacewander

**Comment by spacewander** [comment]
You need to search "how to squash git commit" with your favorite search engine.

**Pull request closed without merging**
