### PR TITLE
fixed #2191

### LINKED ISSUE #2191: bug  zipkin Arguments
- parameters passed when using the function

https://github.com/apache/apisix/blob/3ece377d3ff920a3f46c0fa93312e5d7b276f63f/apisix/plugins/zipkin/codec.lua#L101-L103

- the actual parameters defined by the function
> https://github.com/iresty/opentracing-openresty/blob/master/opentracing/span_context.lua#L33-L37
```lua
-- Public constructor
local function new(trace_id, span_id, parent_id, baggage)
	if trace_id == nil then
		trace_id = generate_trace_id()
....
```

- error log

```text
apisix_1    | 2020/09/09 03:14:32 [error] 24#24: *61 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/zipkin/codec.lua:116: bad argument #1 to '(for generator)' (table expected, got boolean)
apisix_1    | stack traceback:
apisix_1    | coroutine 0:
apisix_1    |   [C]: in function '(for generator)'
apisix_1    |   /usr/local/apisix/apisix/plugins/zipkin/codec.lua:116: in function 'inject'
apisix_1    |   /usr/local/apisix/apisix/plugins/zipkin.lua:156: in function 'phase_fun'
apisix_1    |   /usr/local/apisix/apisix/init.lua:130: in function 'run_plugin'
apisix_1    |   /usr/local/apisix/apisix/init.lua:315: in function 'http_access_phase'
apisix_1    |   access_by_lua(nginx.conf:167):2: in main chunk, client: 172.16.215.41, server: , request: "POST /event/xxxx HTTP/1.1", host: "172.16.210.58:9080"
```

### PR DESCRIPTION
**Pull request by dickens7**
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by moonming** [comment]
```
    apisix/plugins/zipkin/codec.lua:41:13: value assigned to variable sample is unused
```
please remove `sample` variable, thx

**Comment by dickens7** [comment]
I think it’s not a good idea to remove the sample variable, I moved the sample decision logic to create_tracer function. Keep upstream decided to sample the request, we do too.
发送自 Windows 10 版邮件

发件人: Wen Ming
发送时间: 2020年9月9日 16:20
收件人: apache/apisix
抄送: seven dickens; Author
主题: Re: [apache/apisix] fixed #2191 (#2193)

    apisix/plugins/zipkin/codec.lua:41:13: value assigned to variable sample is unused
please remove sample variable, thx

**Comment by moonming** [comment]
thx, it will be better if you can add test cases.

**Comment by moonming** [comment]
> thx, it will be better if you can add test cases.

ping @dickens7

**Comment by dickens7** [comment]
> thx, it will be better if you can add test cases.

I'm sorry to be a little busy these few days, maybe a few days later

**Review by moonming — APPROVED** [review]

**Review by membphis — APPROVED** [review]

**Pull request merged**
