### PR TITLE
docs: default value  correction in include_in_response

### PR DESCRIPTION
**Pull request by iamayushdas**
### What this PR does / why we need it:

include_in_response default value has been edited to ` true` according to request-id architecture
issue: https://github.com/apache/apisix-dashboard/issues/1960

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by iamayushdas** [comment]
cc @Yiyiyimu

**Review by spacewander — COMMENTED** [review]
Please fix the meaningless title.

**Comment by spacewander** [comment]
This is an example of a valid title: https://github.com/apache/apisix/pull/4593 "docs: fix standalone mode yaml config"

**Comment by juzhiyuan** [comment]
@iamayushdas Hi, thanks for your contributions! But please update your PR to have better content:

1. Please use a meaningful title, tells users what happened, and what this PR does? (be clearer as more as possible);
2. If this PR is updating the docs, please update both the English version and the Chinese version at least.

Share with you an article: https://maddevs.io/blog/how-to-make-a-proper-description-for-a-pull-request/

**Review by spacewander — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
