### PR TITLE
chore: `limit-req` plugin code optimization #2448

### PR DESCRIPTION
**Pull request by tashiya-menuri**
### What this PR does / why we need it:
Fix for the issue https://github.com/apache/apisix/issues/2448

### CODE REVIEW

**Comment by Firstsawyou** [comment]
截屏2020-10-31 下午8 39 47
We need to fix the test case `limit-req.t`

**Comment by Firstsawyou** [comment]
image

We need to fix the test case `limit-req.t`

**Comment by tashiya-menuri** [comment]
@Firstsawyou I am working fixing the test cases. Will update the PR once done.

**Comment by Firstsawyou** [comment]
Hi，@tashiya-menuri  
The test case has not been fixed yet, do you need help?

**Comment by membphis** [comment]
ping @tashiya-menuri

**Comment by tashiya-menuri** [comment]
@membphis @Firstsawyou I will take a look on this.

**Comment by Firstsawyou** [comment]
Hi, @tashiya-menuri   Do you need help?

**Comment by tashiya-menuri** [comment]
@Firstsawyou Yes, Any pointers to that help me to complete this will be highly appreciated.

**Comment by Firstsawyou** [comment]
> @Firstsawyou Yes, Any pointers to that help me to complete this will be highly appreciated.

You need to `merge` the master branch code first.

**Comment by Firstsawyou** [comment]
> @Firstsawyou Yes, Any pointers to that help me to complete this will be highly appreciated.

@tashiya-menuri 
You need to solve it like this:
1. 1. You need to merge the master branch code locally.
2. Delete the following test cases：
https://github.com/apache/apisix/blob/a6fbcce2c27f38fb93c94e149fd7fa423c3d5f9d/t/plugin/limit-req.t#L629-L700

**Pull request closed without merging**
