### PR TITLE
docs: Added Keyword API Gateway

### LINKED ISSUE #7218: docs: add `API Gateway` keywords in English and Chinese docs
### Current State

only Apache APISIX, no API Gateway keyword.

### Desired State

see https://github.com/apache/apisix/pull/7217

### PR DESCRIPTION
**Pull request by Ajay-singh1**
### Description

Added Keyword API Gateway

Better SEO of the site

Fixes #7218 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by Neilblaze** [comment]
@Ajay-singh1 Thanks! Could you squash all commit messages into a single one?

**Comment by Neilblaze** [comment]
@Ajay-singh1 Also, before you do that, switch to master branch, update it to upstream, create a new branch from the master, make changes, commit and create the pull request.

**Review by Neilblaze — CHANGES_REQUESTED** [review]
@Ajay-singh1 Also, before you do that, switch to the master branch, update it to upstream, create a new branch from the master, make changes, commit, and create the pull request.

**Review by navendu-pottekkat — COMMENTED** [review]
Adding to the keywords list might be good, but I don't see the need to forcefully change APISIX to APISIX API Gateway everywhere.

**Comment by Ajay-singh1** [comment]
> Adding to the keywords list might be good, but I don't see the need to forcefully change APISIX to APISIX API Gateway everywhere.

I have rectified it.

**Comment by Neilblaze** [comment]
@Ajay-singh1 I'm repeating, follow [this](https://github.com/apache/apisix/pull/8966#pullrequestreview-1319405941) first and then squash all commits into a single one. Make sure to perform a Sign-Off.

If you can't then lemme know, I'll *cc* you in a different PR which I'll open once you confirm.

**Comment by Ajay-singh1** [comment]
I don't know how to squash all the commits.I am afraid it can lead to merge conflicts.Can you redirect me to a different PR?

Thanks for your review.

**Comment by Neilblaze** [comment]
@Ajay-singh1 you can close this issue too. Make sure to close the duplicate ones too!

**Pull request closed without merging**
