### PR TITLE
fix: ios12 CORS error

### LINKED ISSUE #6003: request help: the cors plugin does not force the use of expose_headers
### Issue description

cors插件会开启expose_headers参数，
`expose_headers: "*" `  会触发ios12的bug。
或者就要列出所有的headers，有很多自定义的headers时就会变得很麻烦

### Environment

---

### PR DESCRIPTION
**Pull request by JuwanXu**
### Description
fix ios12 CORS error
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
image

Fixes #6003

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
What happens to ios12 if it is set?

**Comment by JuwanXu** [comment]
> What happens to ios12 if the Access-Control-Expose-Headers is set to `*`?

This will cause a cross-origin error

**Comment by monkeyDluffy6017** [comment]
I don't think it's necessary to change the default value.
Support for wildcards in the Access-Control-Allow-Headers header was added to the living standard.
https://fetch.spec.whatwg.org/#http-new-header-syntax
We should follow the standard.

**Comment by monkeyDluffy6017** [comment]
Maybe you could add tips about this in the doc?

**Comment by monkeyDluffy6017** [comment]
I will close this PR because no changes are required.
If anyone wants to add tips, feel free to submit another pr

**Pull request closed without merging**
