### PR TITLE
change: remove backslash before slash when encoding

### PR DESCRIPTION
**Pull request by Lewisyixin**
### Description
Remove backslash before slash  when setting  routes to etcd or generating log to local files.
The backslash is from lua-cjson and  it can be turned off by default.
https://github.com/openresty/lua-cjson/#encode_escape_forward_slash

Fixes (https://github.com/apache/apisix/issues/7785)
Fixes (https://github.com/apache/apisix/discussions/7606)

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Comment by moonming** [comment]
Is this a break change？

**Comment by Lewisyixin** [comment]
Exactly, I can't guarantee it.  The first time I  encountered this kind of problem is when dealing with data in etcd((https://github.com/apache/apisix/discussions/7606)) . Then I found it was caused by lua-json and avoid it by turning off `json.encode_escape_forward_slash` in my own plugin next time.
When I found other people meeting the same problem in https://github.com/apache/apisix/issues/7785 I helped them param and asked [spacewander](https://github.com/spacewander) if this param can be default turned off in `apisix.core.json` to avoid backslash before slash when json encoding. He let me to try to submit a PR.
I learned this param from https://github.com/openresty/lua-cjson/#encode_escape_forward_slash and used it in my plugin for some months.  But determining whether it will affect other components in apisix is  maybe beyond my ability.

**Review by spacewander — COMMENTED** [review]
Could you add a test like https://github.com/apache/apisix/blob/cffa4b69f9080707d100fbe856f251054cc8cba4/t/core/json.t#L132?

**Comment by spacewander** [comment]
There are some broken tests:
https://github.com/apache/apisix/runs/8062783800?check_suite_focus=true
https://github.com/apache/apisix/runs/8062783743?check_suite_focus=true

I have checked them and all of them are about extra `\` before `/` in the expected string.

**Comment by tzssangglass** [comment]
> Is this a break change？

Yes, because the format of the json parsing has changed.

**Comment by Lewisyixin** [comment]
> Could you add a test like
> 
> https://github.com/apache/apisix/blob/cffa4b69f9080707d100fbe856f251054cc8cba4/t/core/json.t#L132
> 
> ?

Hi @spacewander  do you mean let me to add this test case result into json.t?

```
=== TEST 7: json encode with encode_escape_forward_slash(false)
    location /t {
        content_by_lua_block {
            local json = require("cjson.safe")
            local data = json.encode({uri="/api1/apisixtest"})
            ngx.say(data)

            json.encode_escape_forward_slash(false)
            local data = json.encode({uri="/api1/apisixtest"})
            ngx.say(data)
        }
    }
--- response_body
{"uri":"\/api1\/apisixtest"}
{"uri":"/api1/apisixtest"}
```

**Pull request closed without merging**
