### PR TITLE
bugfix: service discovery duplicate request service information in Eureka #2076

### PR DESCRIPTION
**Pull request by frank0417**
### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible?

### CODE REVIEW

**Comment by frank0417** [comment]
fix #2076

**Comment by membphis** [comment]
please rebase your branch with `master`

**Comment by moonming** [comment]
the same as https://github.com/apache/apisix/pull/1989?

**Comment by frank0417** [comment]
> the same as #1989?

It's not the same problem.

I will cancel this pull request.

**Comment by moonming** [comment]
> > the same as #1989?
> 
> It's not the same problem.
> 
> I will cancel this pull request.

Is this PR is still useful?

**Pull request closed without merging**
