### PR TITLE
docs: fix the broken links

### PR DESCRIPTION
**Pull request by Ajay-singh1**
### Description

Fixes # (issue)
#11217 
### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by kayx23 — CHANGES_REQUESTED** [review]
please use relative paths

**Comment by Ajay-singh1** [comment]
@kayx23 Okay

**Comment by Ajay-singh1** [comment]
@kayx23 I have done the necessary changes kindly review it.

**Comment by kayx23** [comment]
image

It shows no change 💭

**Comment by Ajay-singh1** [comment]
@kayx23 Why is it so I have changed the files you can verify it through the commmit logs?

**Comment by Ajay-singh1** [comment]
Let me open another PR.

**Pull request closed without merging**
