### PR TITLE
feature: divide config.yaml into two files config-custom.yaml & confi…

### LINKED ISSUE #1923: feature: Divide config.yaml into two files config-custom.yaml & config-default.yaml
### Issue description
1. When I deploy APISIX, only a small amount of configuration needs to be modified in conf.yaml.
2. When the APISIX version is upgraded, some configuration items may be added, and these configuration items may be ignored by the user and cause errors.

proposal
1.Divide config.yaml into two files config-custom.yaml & config-default.yaml.
2.`config-default.yaml` is the most complete configuration.
3.`config-custom.yaml` define the user customized configuration.
4. merge the two config file, get final config.

demo
config-custom.yaml
```YAML
apisix:
  node_listen: 80 
  allow_admin:
    - 10.0.0.0/24 
  admin_key:
    -name: "admin"
      key: asdfji213k335f136f87ad84b625c8df
etcd:
  host:
    - "http://10.10.10.2:2379"
    - "http://10.10.10.3:2379"
    - "http://10.10.12.3:2379"
```
config-default.yaml keep the same with APISIX version

generate the final configuration using `config-custom.yaml` to cover `config-default.yaml`.

### Environment

* apisix version 1.4
* OS:

### PR DESCRIPTION
**Pull request by membphis**
…g-default.yaml .

fix #1923 .

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible?

### CODE REVIEW

**Comment by nic-chen** [comment]
LGTM.
But how about allow user to specify the path of `config.yaml`?

**Comment by membphis** [comment]
> How about allowing user to specify the path of `config.yaml` ?

that is another feature, we can implement it in a single PR

**Comment by nic-chen** [comment]
this pr is still a draft now..

**Comment by membphis** [comment]
> this pr is still a draft now ?

missing doc. I'll add this later. but this feature is ready.

**Comment by nic-chen** [comment]
need to resolve conflicts.

**Pull request merged**
