### PR TITLE
chore: remove spellcheck for `push`

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

### What this PR does / why we need it:
~The original markdown-link-check use gaurav-nelson/github-action-markdown-link-check in github actions, which is not allowed for Apache project and aborted for a while. Replace it with install node.js and npm install markdown-link-check~ duplicate of #3197, reverted from this pr

There is no need to `spellcheck` for `push`, when `pull_request` already checked and merging branches won't affect that.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by jbampton** [comment]
Possible duplicate #3197

**Comment by Yiyiyimu** [comment]
> Possible duplicate #3197

Good to know that. Thanks for remind!

**Comment by membphis** [comment]
#3197 has been merged

can we need to close this PR?

**Comment by Yiyiyimu** [comment]
> close this PR?
No I reverted the part duplicated of #3197, the rest one is new.

**Review by spacewander — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Pull request merged**
