### PR TITLE
bugfix: use the route's `has_domain` attribute if the route contains upstream object

### PR DESCRIPTION
**Pull request by membphis**
### What this PR does / why we need it:

> step:

1. create a route with an upstream object, and the upstream node contains domain.
2. create a service, no upstream object (eg: only `plugins`).

client request will fail, we will got  `502`, because the domain of the upstream node is not parsed by DNS resolver.

> fix way:

as title.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by Firstsawyou — APPROVED** [review]
very fast.

**Comment by gxthrj** [comment]
some checks failed

**Comment by membphis** [comment]
> some checks failed

fail to access GitHub, it should be a network problem. rerun it again.

**Review by gxthrj — APPROVED** [review]

**Review by lilien1010 — APPROVED** [review]
Looks good!

**Review by shuaijinchao — APPROVED** [review]

**Comment by shuaijinchao** [comment]
Follow-up can support dynamic upstream according to request information, cool.

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
