### PR TITLE
docs(build): add guide for install failed on MacOS

### PR DESCRIPTION
**Pull request by kwanhur**
### What this PR does / why we need it:

Add user guide, explain failure reason when `make install` under MacOS

#6225 
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Comment by tzssangglass** [comment]
I think we don't need to add tips on building on Macos to this document. This document is not geared towards MacOS.

**Comment by kwanhur** [comment]
> I think we don't need to add tips on building on Macos to this document. This document is not geared towards MacOS.

enn, maybe users face the same problem under different os, not only MacOS.

To be continue, I want to known that:

1. any need to add cognate guides?
2. where place it will be better, like [FAQ](https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md) or other?

**Comment by spacewander** [comment]
I think people can find https://github.com/apache/apisix/issues/6225 by the search engine, so there is no need to add it in the doc. And it seems more like a general Mac permission problem instead of APISIX's problem.

**Comment by kwanhur** [comment]
Hope #6225 helps those trapped.

**Pull request closed without merging**
